### ISSUE TITLE
Using "valueFormatter" does not work in a callback

### ISSUE THREAD

**Issue by alisonmoss3** [plotly/dash-ag-grid#108]
I am using version 2.0.0a4. 

I have a table that may change based on a variety of inputs. If I pass the table directly to the layout, it works fine. However, if I try to pass the 'columnDefs' as an output in a callback the table renders but the anything used for valueFormatter is ignored

**Comment by AnnMarieW** [comment]
Hi @alisonmoss3 
Thanks for reporting, but I can't duplicate the issue.  Can you please make a reproducible example?

```python

from dash import Dash, html, Input, Output
import dash_ag_grid as dag
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/solar.csv")

app = Dash(__name__)

columns1 =  [{"field": i, "valueFormatter": {"function":"'😀' + params.value"}} for i in df.columns]
columns2 =  [{"field": i} for i in df.columns]

grid = dag.AgGrid(
    id="quickstart-grid",
    rowData=df.to_dict("records"),
    columnDefs=columns1,
    columnSize="sizeToFit",
)

app.layout = html.Div([html.Button("Toggle Col",id="btn",n_clicks=0),grid])


@app.callback(
    Output("quickstart-grid", "columnDefs"), Input("btn", "n_clicks")
)
def toggle_col(n):
    if n % 2 == 0:
        return columns1
    return columns2


if __name__ == "__main__":
    app.run_server(debug=True)


```
![ag_not_bug](https://user-images.githubusercontent.com/72614349/226712640-6f850438-1b13-43ff-b826-6639624fb147.gif)

**Comment by alisonmoss3** [comment]
Hi @AnnMarieW Thanks so much for responding! 

I have used your example and adapted it to be similar to one that I am using and it does seem to be working alright. Not sure what my problem was originally but I can use this as a better basis to compare. 

Thanks so much and sorry for the trouble!

**Comment by AnnMarieW** [comment]
OK, no problem, I'm happy to help!  I'll close this issue now but please feel free to re-open it if you still have an issue.

Also, if you make something cool with dash-ag-grid or figure out some feature that's not documented yet, please share a minimal example here or on the Dash forum :slightly_smiling_face:
