### ISSUE TITLE
Feature Request -- return filter query 

### ISSUE THREAD

**Issue by alisonmoss3** [plotly/dash-ag-grid#109]
Hello! 

Thank you so much for making this package public, it is AMAZING!! 

I did have one request I was hoping could be added. 

I'm doing a lot of work with filtering tables and storing the results alongside the query, and I see that you can pull out the resulting data using virtualRowData but I was wondering if there is any way to access the filter query on that table from a callback. 

For example, if I start with a table of 100 rows and filtering on 'column A > 2' results in 50 rows, I can access those 50 rows of data but I can't see a way to retrieve 'column A > 2'. With more complex filters on multiple columns this would be extremely helpful. 

Thank you!

**Comment by BSd3v** [comment]
Hello @alisonmoss3,

Yes, this is often requested and can be very helpful. We will add it before the full release of 2.0.

**Comment by alisonmoss3** [comment]
Thank you! Looking forward to it!
