### ISSUE TITLE
rowTransaction.update cancels row selection 

### ISSUE THREAD

**Issue by danton267** [plotly/dash-ag-grid#114]
The code to recreate is in the docs: https://dashaggrid.pythonanywhere.com/clientside-data/updating-data

when a row is selected and `rowTransaction.update` is performed, it removes the prior row selection.

Expected behaviour: after `rowTransaction.update` keep previously selected rows: https://www.ag-grid.com/react-data-grid/server-side-model-updating-transactions/

**Comment by BSd3v** [comment]
Hello @danton267,

This only pertains to if you are updating the same line, is this correct?

If so, for your specific use-case, you will need to pass the updated line info to also maintain the selection. This is due to the line info being updated and grid cannot maintain the selection.
