### ISSUE TITLE
Creating dag.AgGrid() with autoSizeAllColumns=True crashes in v2.0a4

### ISSUE THREAD

**Issue by romanov-o** [plotly/dash-ag-grid#126]
Creating dag.AgGrid() with `autoSizeAllColumns=True` crashes with the error message `Cannot read properties of undefined (reading 'getColumnState')` in v2.0a4

**Comment by BSd3v** [comment]
Correct, this was fixed in version a5. Could you please update to that version and try again? 🙂

**Comment by romanov-o** [comment]
Confirmed - no errors in v a5. Thanks!
