### ISSUE TITLE
Incorrect result of dag.AgGrid() with columnSize='autoSizeAll' in v2.0a4

### ISSUE THREAD

**Issue by romanov-o** [plotly/dash-ag-grid#127]
Creating dag.AgGrid() with columnSize='autoSizeAll' results in all columns having the same size in v2.0a4

**Comment by BSd3v** [comment]
Hello @romanov-o,

Could you please provide some code for this issue?

If you have headers that are about the same size, this will cause the columns to be about the same size.

**Comment by romanov-o** [comment]
The probrem appears when the AG Grid is created on a [dbc.Tab component](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/tabs/) which is not visible at the time of creation. It seems like the tab wich has not been activated has its width = 0 thus width of all columns of the grid = minWidth. When the tab is activated its width is set to some value but the AG Grid remains in the previous state with minimum columns width.

Here's the code to reproduce the effect:

```python
import dash
import dash_bootstrap_components as dbc
from dash import html
import dash_ag_grid as dag
import pandas as pd

app = dash.Dash(__name__, title="Transactions", external_stylesheets=[dbc.themes.BOOTSTRAP])

df = pd.DataFrame({'Date': ['2023-04-01', '2023-04-02', '2023-04-03'],
                   'Name': ['Donovan Kaolin', 'Richelle Miles', 'Satchel Novalee'],
                   'Amount': [1234.56, 456.78, 7890.12]})

columnDefs = [{'headerName': col, 'field': col} for col in df.columns]

defaultColDef = {
    'filter': True,
    'floatingFilter': False,
    'resizable': True,
    'sortable': True,
    'editable': False,
}

table = dag.AgGrid(
    id='ag-grid',
    className='ag-theme-balham',
    columnDefs=columnDefs,
    defaultColDef=defaultColDef,
    columnSize='autoSizeAll',
    rowData=df.to_dict('records'),
)

app.layout = html.Div([
    dbc.Tabs([
        dbc.Tab([], label="First tab" ),
        dbc.Tab([ table ], label="Tab with the AG Grid")
    ])
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by BSd3v** [comment]
Alright, that makes a lot of sense. 

I don't know if there is a way for us to manage this with the component, as to listening to alterations on visibility could lead to some drag on performance. 

You could have a callback designed to give the autoSizeAll=True, the first time that you get the visibility.

**Comment by AnnMarieW** [comment]
This is actually a Dash issue and not an AG Grid issue.  
See https://github.com/plotly/dash/issues/1296 and https://github.com/plotly/dash/issues/2436

**Comment by romanov-o** [comment]
> You could have a callback designed to give the autoSizeAll=True, the first time that you get the visibility.

Yes, this solves the issue. Thanks!
