### ISSUE TITLE
Using dcc.Link()

### ISSUE THREAD

**Issue by salam-abdul** [plotly/dash-ag-grid#136]
Hi,

I have tried a few different way but have not gotten this to work. I'm hoping I missed something simple. Is there any way to add a dcc.Link() to the dashAgGrid as a column or use a callback to achieve the "no refresh" navigation the dcc.Link() provides? This would be very beneficial in a multipage Dash app. 

Thank you!

**Comment by salam-abdul** [comment]
Sorry for submitting, I see this is already noted in Dash AG Grid V2.0 Status #15

**Comment by AnnMarieW** [comment]
Hi @salam-abdul 

Using `dcc.Link` in a AG Grid cell is not available yet, however, if you upgrade to dash 2.9.2, it is now possible to navigate from a callback without refreshing the screen by using the new "callback-nav" option for the `refresh` prop:

   `dcc.Location(id="url", refresh="callback-nav")`   

There should only be `one dcc.Location` component in your app, and it should be in the main `app.py` file.
