### ISSUE TITLE
Accessing event attributes of AG Grid 

### ISSUE THREAD

**Issue by mkaanerkoc** [plotly/dash-ag-grid#14]
**Problem statement:** event callbacks are not being fired

**Explanation:** I tried to get `modelUpdated` and `viewportChanged` callbacks when filter is applied on `AG-grid` but could not succeeded yet. 

**Version:** 
`dash-ag-grid==2.0.0a1`

**Code snippet:**
```
@app.callback(  Output("chart", "figure"),
                Input("details-table", "modelUpdated"),
                Input("details-table", "viewportChanged"))
def model_updated(data, vp):
    print(data, vp)
    return go.Figure()
```

**Community Forum:**
https://community.plotly.com/t/how-to-capture-viewportchanged-or-modelupdated-events-in-the-ag-grid/72139

**Comment by AnnMarieW** [comment]
The forum post has been updated to show how to use `virtualRowData` in a callback
