### ISSUE TITLE
Bug: built-in JavaScript error on expand/collapse of row groups in v2.0.0rc1

### ISSUE THREAD

**Issue by romanov-o** [plotly/dash-ag-grid#160]
JavaScript error is thrown when expanding/collapsing row groups in v2.0.0rc1.
This error does not appear in the previous v2.0.0a5 release.

To reproduce, run the following code and expand all groups and then try to collapse them sequentially.

```python
from dash import Dash
import dash_ag_grid as dag

data = [{'G1':'A', 'G2':'B', 'Data':1000}]
columnDefs=[ {'field'  : col,
              'rowGroup': col in ['G1', 'G2'],
              } for col in data[0] ]
table_categories = dag.AgGrid(
    columnDefs=columnDefs,
    rowData=data, 
    enableEnterpriseModules=True,
)

app = Dash(__name__)
app.layout = table_categories

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by AnnMarieW** [comment]
Hi @romanov-o 

Thanks for reporting!

 @BSd3v discovered this bug earlier today and it's already fixed. :tada: 
V2.0.0rc2 is ready and will be released soon.

**Comment by BSd3v** [comment]
rc2 has been released, going to close this. Feel free to open if the issue persists.
