### ISSUE TITLE
top row disappearing when sorting 

### ISSUE THREAD

**Issue by kiwifb** [plotly/dash-ag-grid#165]
I am currently experimenting moving some of my tables from simple dash-bootstrap-component to dash-ag-grid (to gain features where it makes sense). I have been toying with with 2.0.0rc1 and now 2.0.0rc2 and when I click on a column header to sort the table by that column, the top row usually disappear. It usually reappear when clicking again to sort the other direction, but then on some tables, it disappear as well when clicking a third time to remove the sorting. It consistently disappear on the first sorting click.
The tables are build on this model
```
dag.AgGrid(
        id="outstanding_gd",
        rowData=outstanding_df.to_dict("records"),
        columnDefs=[{"field": i} for i in outstanding_df.columns],
        defaultColDef={"resizable": True, "sortable": True, "filter": True},
        columnSize="sizeToFit",
        getRowId="params.data.State",
        dashGridOptions={"domLayout": "autoHeight"},
    )
```
The number of row is small so `autoHeight` does not cause issues. In fact, I regularly have less than 4 rows in those tables which means that even with `autoHeight`, I have some blank space below the table.

**Comment by kiwifb** [comment]
When I say the row disappear, I should add that I have a blank row instead.

**Comment by BSd3v** [comment]
Hello @kiwifb,

That is very strange indeed.

You shouldnt need to place `"domLayout":"autoHeight"`.

Could you possible provide some data and the whole code to reproduce? We have a bunch of tests that perform sorting and in my interactions with the sorting and filtering, I havent encountered anything like what you are describing.

**Comment by kiwifb** [comment]
That's a bit awkward to provide the whole code, it is a multi page dash app that query a mariadb database. I may try to figure a minimum case.

As for the `domLayout`, yes, may be not now. I used to have three tables on the one page, and without it, things were not pleasant because of the space between tables. I moved them to individual tabs, so it should now be irrelevant. That whole height business is rather annoying, but it is a different issue.

**Comment by BSd3v** [comment]
You could also provide a snapshot of the grid hiding the top row, do you have blank rows in the dataset?

**Comment by kiwifb** [comment]
There should be no blank rows in the data sets. I can provide snapshots, I should remove some info first.

**Comment by BSd3v** [comment]
Do you have any callbacks associated with the filtering/sorting or `virtualRowData`?

**Comment by kiwifb** [comment]
None of that. The only callback on that page is tab selection.

**Comment by kiwifb** [comment]
Of course once I removed sensitive columns, it behaved differently. The top row only disappeared on the third click to restore the original order.
![dag-initial](https://user-images.githubusercontent.com/151475/234732571-d35b5b23-45c6-44a6-a949-615887ceb520.png)
![dag-restore](https://user-images.githubusercontent.com/151475/234732572-0ee8c5e6-24f7-4316-afad-1ed3da88a5e5.png)

**Comment by BSd3v** [comment]
You have down that your `getRowId="params.data.State"`, do you have repeating states?

**Comment by kiwifb** [comment]
Not that I know off, I copied blindly the quickstart example. That's one of the bit I do not really understand at this stage.

**Comment by BSd3v** [comment]
`getRowId` represents and tells the grid about the unique identifiers of the information. If you actually dont have this information, then you shouldnt be providing it.

What you are pointing to, was something that I actually saw when starting to work with the rowId's when adding and testing adding data.

I recommend removing the `getRowId` statement, and see if the issue persists.

**Comment by kiwifb** [comment]
That fixed it. Thanks. I am still not sure what the RowId stuff is supposed to be, even from your explanation. I probably miss a bit of background, I'll dig the documentation. Again, thanks for your quick help.

**Comment by BSd3v** [comment]
Check out here:

https://dashaggrid.pythonanywhere.com/rows/row-ids

**Comment by kiwifb** [comment]
I think I get it now. Any reason it is actually in the quick start example? I would not expect to be the only to code by copy pasting examples and adapting.

**Comment by BSd3v** [comment]
Setting `getRowId` is necessary for things like allowing the grid to animate changes to things like `rowData` or `rowTransaction` pushed, which is a really cool feature.

For your purposes, I'd set it to be `params.data.projectcode` assuming that this would be unique. :)

**Comment by kiwifb** [comment]
I see, yes. I have a few unique keys that I can use that way.

**Comment by BSd3v** [comment]
The cool thing, is you can even combine columns like this:

`getRowId="params.data.projectcode + '-' + params.data.date"` resulting in "RCC084-2020-04-28" for the top one.

The is especially helpful for things like PO's and items, where the PO may be repeat across several rows, but the PO-item is going to be unique. 😄

**Comment by kiwifb** [comment]
Fancy.
