### ISSUE TITLE
[Feature Request] - add rowData to persistence

### ISSUE THREAD

**Issue by AnnMarieW** [plotly/dash-ag-grid#178]
As [requested on the forum](https://community.plotly.com/t/how-to-add-persistence-to-dash-ag-grid/74944/3?u=annmariew) - add ability to make  `rowData` persistent

Currently only selectedRows are included in `persisted_props` by default. Should others be added? 
- `columnState`, 
- `filterModel`
-  `paginationInfo`

**Comment by BSd3v** [comment]
`rowData` by its nature gets adjusted by the grid in place, this isnt something that we can currently address, you'll need to use the workaround of a `dcc.Store` in order to achieve the desired result.
