### ISSUE TITLE
Some columns ignore columnSize="autoSize"

### ISSUE THREAD

**Issue by roman-kachanovsky** [plotly/dash-ag-grid#185]
If I don't missing something in docs, `columnSize="autoSize"` with default `columnSizeOptions` is equivalent to `autoSizeAllColumns` option. But some columns don't want to be autosized by default.

Code snippet:
```python
import dash_ag_grid as dag
import pandas as pd
from dash import Dash, html


app = Dash(__name__)

df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/ag-grid/olympic-winners.csv"
)

columnDefs = [
    {"field": "age"},
    {"field": "year"},
    {"field": "date"},
    {"field": "gold"},
    {"field": "silver"},
    {"field": "bronze"},
    {"field": "total"},
    {"field": "athlete"},
    {"field": "country"},
    {"field": "sport"},
]

app.layout = html.Div(
    [
        dag.AgGrid(
            columnDefs=columnDefs,
            rowData=df.to_dict("records"),
            columnSize="autoSize",
            defaultColDef={"resizable": True, "sortable": True, "filter": True},
        ),
    ],
    style={"margin": 20},
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

Result:
<img width="1393" alt="image" src="https://github.com/plotly/dash-ag-grid/assets/16509052/7c93b228-663c-4960-8523-dbfd7c12bd4f">

The same behaviour I see with enabled `enableEnterpriseModules` feature:
<img width="1392" alt="image" src="https://github.com/plotly/dash-ag-grid/assets/16509052/a64b23cc-fefc-48e5-94bf-fd5ee865f6ae">

Applying "Autosize All Columns" from UI also shows that all columns can be fitted in the viewport, so it shouldn't be related to column virtualization and resizing of visible columns only:
<img width="1392" alt="image" src="https://github.com/plotly/dash-ag-grid/assets/16509052/185f9429-6665-489c-8f95-0b33e74b7511">

**Comment by BSd3v** [comment]
Hello @roman-kachanovsky,

This seems to be related to the vision of the grid at start. The API expands the grids based upon the rendered vision of the cells. It's all about the timing of when the API is triggered.

I dont know if there is a way for use to delay the trying to adjust the columnSize any longer. If you want, you can disable the initial `columnSize` by passing `None`, this will apply the grid's default spacing.

**Comment by roman-kachanovsky** [comment]
@BSd3v hmm, okay. We had some problems with auto-sizing in previous versions of dash-ag-grid too, which we avoided by setting up of "default" column widths. And we can keep it, but it interesting why the feature has no consistency in working between initial state and applying of "Autosize All Columns" from menu. Also, I'm not clearly understand how the grid determines "visible" area and decide how to resize columns. Here the example of the issue from real app:
<img width="527" alt="image" src="https://github.com/plotly/dash-ag-grid/assets/16509052/15fbecc4-10da-4d46-ab65-373ec33aff55">
"Date of creation" column is the last column that partially fits in my screen. Next column "Creator" plus 3 addtional columns on the right are out of the view. But only "Creator" is squeezed. Other invisible columns seem okay. These things make "autoSize" option kinda useless for quite big tables, imho.

**Comment by BSd3v** [comment]
I think it's because Creator is almost in view perhaps, while the others are in view so they don't get touched? I can troubleshoot it some. 

But, you could use `columnSize=None`, then let the user size the columns however they want and save the columnState to reload the state whenever the grid is loaded for them.

**Comment by roman-kachanovsky** [comment]
We resolved that issue by `suppressColumnVirtualisation=True`. Our tables have 5-15 columns, so I guess it won't affect our performance too much.

**Comment by BSd3v** [comment]
Ah, that makes sense now. 

It is definitely something that is a bit of a pain for sure.

**Comment by alexcjohnson** [comment]
Dug into this a little... AG Grid mentions this in their [docs](https://www.ag-grid.com/javascript-data-grid/column-sizing/#auto-size-columns) (we have a matching note in our [column sizing docs](https://dash.plotly.com/dash-ag-grid/column-sizing#auto-size-columns)) as an either-or with no proposed workaround:

> Column Virtualisation is the technique the grid uses to render large amounts of columns without degrading performance by only rendering columns that are visible due to the horizontal scroll positions. For example, the grid can have 1,000 columns with only 10 rendered if the horizontal scroll is only showing 10 columns.
> 
> To get around this, you can turn off column virtualisation by setting grid property `suppressColumnVirtualisation=true`. The choice is yours, whether you want column virtualisation working OR auto-size working using off-screen columns.

I could imagine a feature where a columns that hasn't been rendered yet but is intended to be autosized would be marked internally by AG Grid for autosizing at the moment it scrolls into rendering. But that would need to be done by AG Grid, if we try to do it from the outside it would be unlikely to work very well.

So I'm going to close this issue as out-of-scope for us. Thanks for the discussion @roman-kachanovsky!
