### ISSUE TITLE
getRowId="params.data.index" causes different issues

### ISSUE THREAD

**Issue by aknse** [plotly/dash-ag-grid#197]
I am using a few different AG Grids in my dash app. All originally had getRowId="params.data.index", but they all had different bugs that appeared to be resolved when removing that line.

- In one table, I display data that is filtered with changes to a graph. When I change the graph to filter the data, the 1st group remained, and the second group was added to the bottom of the table. When I changed to a 3rd group, the data from the 3rd group replaced the data from the 2nd group, but the 1st remained. Removing getRowID fixed this issue.
- In another table, I have "rowSelection": "single", but selecting another row would still highlight all previously selected rows. In addition, when switching between tabs in my dash app, all rows would be selected when I return to the tab with the table. Removing getRowID appears to have fixed this issue, as well.
- I also experienced the issue with the top row disappearing (and also hiding the data underneath) as outlined in https://github.com/plotly/dash-ag-grid/issues/165. Removing getRowID worked.

**Comment by BSd3v** [comment]
Hello @aknse,

I am assuming this is because your index is driven by the df, which means that the values arent static. To allow for using a rowId other than the one generated by the grid, you need to make sure that your datasource provides a uniquie identifier.

This can be expanded to be concatenated fields as well, making this a pretty powerful tool.

To concatenate, you need to provide something like this:

```
getRowId="params.data.uid1 + '|' + params.data.pono"
```

**Comment by aknse** [comment]
Thanks for the insight! I'll explore the use of getRowId in the future since I don't need it right now. I'll close this ticket since it appears that this likely related to how I was using it.

**Comment by aknse** [comment]
> Hello @aknse,
> 
> I am assuming this is because your index is driven by the df, which means that the values arent static. To allow for using a rowId other than the one generated by the grid, you need to make sure that your datasource provides a uniquie identifier.
> 
> This can be expanded to be concatenated fields as well, making this a pretty powerful tool.
> 
> To concatenate, you need to provide something like this:
> 
> ```
> getRowId="params.data.uid1 + '|' + params.data.pono"
> ```

I know this is a closed ticket, but I'm implementing something where I want the index driven by the dataframe. The dataframe is a subset of a much larger dataset, which can change as I change the group of data I want to view. The values aren't static and they never will be. To add to that, I want to create buttons that allow the user to traverse the dataframe to generate a graph, so having the index driven by the dataframe is critical to have this work, unless there's another method that you suggest.

How would you recommend I handle this situation?

**Comment by BSd3v** [comment]
Hey @aknse,

Can you post this instead on the plotly forums as a dash question?
