### ISSUE TITLE
filterOptions not working

### ISSUE THREAD

**Issue by rushi-jariwala** [plotly/dash-ag-grid#203]
filterOptions not working in the example in docs (https://dashaggrid.pythonanywhere.com/filtering/column-filters-overview)

![image](https://github.com/plotly/dash-ag-grid/assets/50650888/a71e4b64-1745-427b-ab09-eab7747b5b9a)

**Comment by AnnMarieW** [comment]
Hi @rushi-jariwala 

Thanks for reporting - I can verify that this was working in 2.0.0a4, but not in any version after that.

**Comment by rushi-jariwala** [comment]
Thanks for fixing the issue in dev branch. Any updates on timelines for the next release with this fix?

**Comment by BSd3v** [comment]
Should be today, hopefully. 😁
