### ISSUE TITLE
[Feature Request] How to reduce text spacing in a cell?

### ISSUE THREAD

**Issue by yxc8** [plotly/dash-ag-grid#214]
I tried putting "wrapText": True in the dictionary for defaultColDef. However, the spacing between lines looks like double spacing. Is there a way to reduce the spacing between lines?

**Comment by BSd3v** [comment]
Hello @yxc8,

Could you please post this on the plotly forums?

There are ways to make your own custom theme and to adjust these line settings via css.

**Comment by BSd3v** [comment]
There is documentation here to provide more info on styling:
https://dash.plotly.com/dash-ag-grid/cell-styling
https://community.plotly.com/t/text-wrapping-on-words-not-characters-in-dash-ag-grid/77010/3?u=jinnyzor
