### ISSUE TITLE
Table Date filtering not working

### ISSUE THREAD

**Issue by gmouawad** [plotly/dash-ag-grid#217]
Hello,

I am defining a table from a data frame. I have a date field in that df that I need to show it and be able to filter it (equals, in range, etc.)

in my column definition, I coded the below:
{
        "field": "Timestamp",
        "headerName": "Timestamp",
        "filter": "agDateColumnFilter",
        "valueFormatter": {"function": f"d3.timeParse('%d/%m/%Y)(params.data[\"Timestamp\"])"},
        "valueGetter": {"function": f"d3.timeParse('%d/%m/%Y)(params.data[\"Timestamp\"])"},
}

The dates are listed as expected. but when filtering, if I put equals, it doesn't filter; if I put a range, the dates disappear.

Any documentation/examples are highly appreciated. or if you can fix my definition so I can have it working. it will be great.

Thanks

**Comment by AnnMarieW** [comment]
Hi @gmouawad 

You can find more information on date filters here:  https://dash.plotly.com/dash-ag-grid/date-filters

Note the date filter works for dates only, and there cannot be a (non-zero)  time portion of the date.  You can also find more info and examples on this page:  https://dash.plotly.com/dash-ag-grid/d3-value-formatters#formatting-dates-and-times-with-d3-time-format

**Comment by gmouawad** [comment]
> Hi @gmouawad
> 
> You can find more information on date filters here: https://dash.plotly.com/dash-ag-grid/date-filters
> 
> Note the date filter works for dates only, and there cannot be a (non-zero) time portion of the date. You can also find more info and examples on this page: https://dash.plotly.com/dash-ag-grid/d3-value-formatters#formatting-dates-and-times-with-d3-time-format

I removed the time part and it didn't work as well

**Comment by AnnMarieW** [comment]
@gmouawad
Since this is a "how-to" question rather than a bug, let's continue this discussion on the [dash forum](https://community.plotly.com/)

Please include a minimal example with some sample data that can be run to duplicate the issue.  See you on the forum :slightly_smiling_face:

**Comment by gmouawad** [comment]
> Hello,
> 
> I am defining a table from a data frame. I have a date field in that df that I need to show it and be able to filter it (equals, in range, etc.)
> 
> in my column definition, I coded the below: { "field": "Timestamp", "headerName": "Timestamp", "filter": "agDateColumnFilter", "valueFormatter": {"function": f"d3.timeParse('%d/%m/%Y)(params.data["Timestamp"])"}, "valueGetter": {"function": f"d3.timeParse('%d/%m/%Y)(params.data["Timestamp"])"}, }
> 
> The dates are listed as expected. but when filtering, if I put equals, it doesn't filter; if I put a range, the dates disappear.
> 
> Any documentation/examples are highly appreciated. or if you can fix my definition so I can have it working. it will be great.
> 
> Thanks

https://community.plotly.com/t/table-date-filtering-not-working/76813
