### ISSUE TITLE
[Feature Request] Can we have the export to excel/xlsx function if purchase enterprise license. 

### ISSUE THREAD

**Issue by crystle443925** [plotly/dash-ag-grid#218]
The export via excel is quite important feature in ag grid, can you please add this feature for dash as well?

**Comment by BSd3v** [comment]
Hello @crystle443925,

You are able to access this via the `getApi` in a JS clientside callback currently.

**Comment by BSd3v** [comment]
You can find some examples here:

https://community.plotly.com/t/dash-ag-grid-export-data-as-excel/77325/2
