### ISSUE TITLE
Question/Issue regarding starting with rowGroup open 

### ISSUE THREAD

**Issue by liammcknight95** [plotly/dash-ag-grid#219]
Hi, is there any parameter in the column definitions that can be set to have rowGroups start open?

**Comment by AnnMarieW** [comment]
Yes, this is available, it's just not documented yet.  More info on this page https://www.ag-grid.com/react-data-grid/grouping-opening-groups/

You can add `groupDefaultExpanded` to `dashGridOptions`

```
dag.AgGrid(
  dashGridOptions={'groupDefaultExpanded' : -1}

)

```

**Comment by liammcknight95** [comment]
Excellent, thanks AnnMarie
