### ISSUE TITLE
`scrollTo` a `rowId` doesn't work on rows collapsed in `rowGroup`

### ISSUE THREAD

**Issue by Farkites** [plotly/dash-ag-grid#221]
`scrollTo` a `rowId` that is collapsed in a `rowGroup` doesn't work. If the `rowGroup` isn't collapsed it works.

Reproduce bug with this script:
```python
import dash_ag_grid as dag
import dash
from dash import html, dcc, callback, Output, Input
import pandas as pd


app = dash.Dash(__name__)


df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/ag-grid/olympic-winners.csv"
)

columnDefs = [
    # Row group by country and by year is enabled.
    {"field": "country", "sortable": True, "filter": True, "rowGroup": True},
    {"field": "year", "sortable": True, "filter": True, "rowGroup": True},
    {"field": "athlete", "sortable": True, "filter": True},
    {"field": "age", "sortable": True, "filter": True},
    {"field": "date", "sortable": True, "filter": True},
    {"field": "sport", "sortable": True, "filter": True},
    {"field": "total", "sortable": True, "filter": True},
]

app.layout = html.Div(
    [
        dag.AgGrid(
            columnDefs=columnDefs,
            rowData=df.to_dict("records"),
            dashGridOptions={"rowSelection": "multiple"},
            defaultColDef=dict(
                resizable=True,
            ),
            id="grouped-grid",
            enableEnterpriseModules=True,
            licenseKey="LICENSE_KEY_HERE",
            getRowId="params.data.date+params.data.athlete",
        ),
        html.Button("Scroll to index Michael Phelps 24/08/2008", id="button"),
    ]
)


@callback(
    Output("grouped-grid", "scrollTo"),
    Input("button", "n_clicks"),
    prevent_initial_call=True,
)
def scroll_to(n_clicks):
    return {"rowId": "24/08/2008Michael Phelps"}


if __name__ == "__main__":
    app.run_server(debug=True)

```

Screen capture:

https://github.com/plotly/dash-ag-grid/assets/35932204/23dc3406-25dc-43d4-937d-e5e8358b72ea

**Comment by BSd3v** [comment]
I wouldn't label this as a bug, this is obviously the intended purpose of how the grid functions. 

If a row is not visible, it cannot be found in the dom. 

There are a couple ways that something could be grouped, row groupings or tree data. As the dev, you should be able to know which one can apply to your grid. 

We should just use the api to be able to ensure that the row is expanded before trying to scroll to it.

**Comment by BSd3v** [comment]
Here is a version that works:

```
import dash_ag_grid as dag
import dash
from dash import html, dcc, callback, Output, Input
import pandas as pd


app = dash.Dash(__name__)


df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/ag-grid/olympic-winners.csv"
)

columnDefs = [
    # Row group by country and by year is enabled.
    {"field": "country", "sortable": True, "filter": True, "rowGroup": True},
    {"field": "year", "sortable": True, "filter": True, "rowGroup": True},
    {"field": "athlete", "sortable": True, "filter": True},
    {"field": "age", "sortable": True, "filter": True},
    {"field": "date", "sortable": True, "filter": True},
    {"field": "sport", "sortable": True, "filter": True},
    {"field": "total", "sortable": True, "filter": True},
]

app.layout = html.Div(
    [
        dag.AgGrid(
            columnDefs=columnDefs,
            rowData=df.to_dict("records"),
            dashGridOptions={"rowSelection": "multiple"},
            defaultColDef=dict(
                resizable=True,
            ),
            id="grouped-grid",
            enableEnterpriseModules=True,
            # licenseKey="LICENSE_KEY_HERE",
            getRowId="params.data.date+params.data.athlete",
        ),
        html.Button("Scroll to index Michael Phelps 24/08/2008", id="button"),
    ]
)


app.clientside_callback(
    """function (n) {
        const exposeRow = (rowId, id) => {
            grid = dash_ag_grid.getApi(id)
            grid.setRowNodeExpanded(grid.getRowNode(rowId), true, true)
        }
        exposeRow("24/08/2008Michael Phelps", "grouped-grid")
        return {"rowId": "24/08/2008Michael Phelps"}
    }""",
    Output("grouped-grid", "scrollTo"),
    Input("button", "n_clicks"),
    prevent_initial_call=True,
)


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by AnnMarieW** [comment]
Nice example @BSd3v 
Let's leave this open until it's added to the docs :slightly_smiling_face:

**Comment by Farkites** [comment]
> Here is a version that works:
> 
> ```
> import dash_ag_grid as dag
> import dash
> from dash import html, dcc, callback, Output, Input
> import pandas as pd
> 
> 
> app = dash.Dash(__name__)
> 
> 
> df = pd.read_csv(
>     "https://raw.githubusercontent.com/plotly/datasets/master/ag-grid/olympic-winners.csv"
> )
> 
> columnDefs = [
>     # Row group by country and by year is enabled.
>     {"field": "country", "sortable": True, "filter": True, "rowGroup": True},
>     {"field": "year", "sortable": True, "filter": True, "rowGroup": True},
>     {"field": "athlete", "sortable": True, "filter": True},
>     {"field": "age", "sortable": True, "filter": True},
>     {"field": "date", "sortable": True, "filter": True},
>     {"field": "sport", "sortable": True, "filter": True},
>     {"field": "total", "sortable": True, "filter": True},
> ]
> 
> app.layout = html.Div(
>     [
>         dag.AgGrid(
>             columnDefs=columnDefs,
>             rowData=df.to_dict("records"),
>             dashGridOptions={"rowSelection": "multiple"},
>             defaultColDef=dict(
>                 resizable=True,
>             ),
>             id="grouped-grid",
>             enableEnterpriseModules=True,
>             # licenseKey="LICENSE_KEY_HERE",
>             getRowId="params.data.date+params.data.athlete",
>         ),
>         html.Button("Scroll to index Michael Phelps 24/08/2008", id="button"),
>     ]
> )
> 
> 
> app.clientside_callback(
>     """function (n) {
>         const exposeRow = (rowId, id) => {
>             grid = dash_ag_grid.getApi(id)
>             grid.setRowNodeExpanded(grid.getRowNode(rowId), true, true)
>         }
>         exposeRow("24/08/2008Michael Phelps", "grouped-grid")
>         return {"rowId": "24/08/2008Michael Phelps"}
>     }""",
>     Output("grouped-grid", "scrollTo"),
>     Input("button", "n_clicks"),
>     prevent_initial_call=True,
> )
> 
> 
> if __name__ == "__main__":
>     app.run_server(debug=True)
> ```

@BSd3v Thanks! I was thinking on adding this `setRowNodeExpanded` behaviour to the `scrollTo` event, but this works well and we can avoid overloadding the component.
