### ISSUE TITLE
Horizontal scroll bar removal

### ISSUE THREAD

**Issue by gmouawad** [plotly/dash-ag-grid#224]
Hello,

How I can get rid of the horizontal scroll bar below the dash ag grid?
![image](https://github.com/plotly/dash-ag-grid/assets/80507466/c559ec27-1308-42c0-bbf8-2af37f507117)

**Comment by BSd3v** [comment]
Hello @gmouawad,

Could you please post your question on the forum?

This is going to be an issue with styling the div that is holding the grid. 

When posting on the forum, can you please provide a minimal working example of how you have the component setup?

**Comment by gmouawad** [comment]
> Hello,
> 
> How I can get rid of the horizontal scroll bar below the dash ag grid? ![image](https://user-images.githubusercontent.com/80507466/255548328-c559ec27-1308-42c0-bbf8-2af37f507117.png)

it was my div styling issue, disregard, thanks!

**Comment by gmouawad** [comment]
> Hello @gmouawad,
> 
> Could you please post your question on the forum?
> 
> This is going to be an issue with styling the div that is holding the grid.
> 
> When posting on the forum, can you please provide a minimal working example of how you have the component setup?

Hello @BSd3v as mentioned in my last comment, it was a styling issue nothing related to the dash ag grid itself. Thanks a lot
