### ISSUE TITLE
'domLayout': 'autoHeight' goes below other components when grid height grows

### ISSUE THREAD

**Issue by alistairwelchJD** [plotly/dash-ag-grid#231]
As per the AG Grid docs: 

"""When domLayout='autoHeight' then your application should not set height on the grid div, as the div should be allowed flow naturally to fit the grid contents. When auto height is off then your application should set height on the grid div, as the grid will fill the div you provide it.""" https://www.ag-grid.com/javascript-data-grid/grid-size/#grid-auto-height

**Comment by AnnMarieW** [comment]
Hi @alistairwelchJD 

Thanks for bringing this up - we'll add it to the docs.  

In `dash-ag-grid` we have a default height and width set on the grid div - see the [Grid Height docs](https://dash.plotly.com/dash-ag-grid/grid-size)

In order for autoHeight to work correctly with grids taller than the default of 400px, it's necessary to remove the default `height`

```
import dash_ag_grid as dag
from dash import Dash, html, dcc

app = Dash(__name__)

columnDefs = [{"field": "row"}]

data = [{"row": f"Row {i}"} for i in range(15)]

app.layout = html.Div(
    [
        dag.AgGrid(
            id="auto-height-example",
            columnDefs=columnDefs,
            rowData=data,
            columnSize="sizeToFit",
            dashGridOptions={"domLayout": "autoHeight"},
            style={"height": None}
        ),
        dcc.Markdown("Grid size with auto height", ),
    ],
    style={"margin": 20},
)

if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by alexcjohnson** [comment]
@BSd3v and I discussed this, since it’s not obvious that we’ve put `height: '400px', width: '100%'` as the default style for the div, if there are any props that make this default clearly inappropriate we should detect that and respond. And this seems a clear example of that. So I'd rather we treat this as a bug.

**Comment by aliwelchoo** [comment]
Thank you both.

@AnnMarieW, I was making it worse by using an old version where your solution to overwrite the style doesn't work  but I will upgrade and do that for now so thank you!

I've also proposed a code change, that I'll be able to test and clean up further next week
