### ISSUE TITLE
[Bug issue] The rowStyle not working properly when enabling the rowGrouping enterprise 

### ISSUE THREAD

**Issue by crystle443925** [plotly/dash-ag-grid#234]
I would like to bold the whole row when City name = 'Hamburg' using rowStyle, however when I implemented the rowGrouping feature from enterprise, the collapse/expand function of rowGrouping doesnt work properly.

```
RowStyle2 = {
    "styleConditions": [
        {
            "condition": "params.data.City == 'Hamburg'",
            "style": {"backgroundColor": "lavenderblush"},
        },
    ]
}

table = dag.AgGrid(
        id="update-rowdata-grid",
        enableEnterpriseModules=True,
        rowData=df.to_dict('records'),
        columnDefs=colDef,
        columnSizeOptions={"skipHeader":True},
        defaultColDef=dict(
            resizable=True,
            sortable=False,
            filter=False,
        ),
        getRowStyle=getRowStyle2,
        dashGridOptions=dict(
            groupDefaultExpanded=-1,
            groupDisplayType='custom',
            groupHideOpenParents = True
            ),
        className="ag-theme-alpine",
        
        style={"height": "100vh"},
        csvExportParams={"fileName": f"{name}.csv"}
    )
```
![Screenshot 2023-08-14 at 14 50 47](https://github.com/plotly/dash-ag-grid/assets/135717933/023a59e0-fed3-4da5-9d27-161312e27b5c)

**Comment by BSd3v** [comment]
Hello @crystle443925,

This is probably due to an error with how your function is written, you should be testing to see if `City` exists in your row before trying to reference it, something like this might work:

`params.data.City ? params.data.City == 'Hamburg' : false`

If this doesnt work, can you please post more complete example so that we can run it without coming up with info.

**Comment by crystle443925** [comment]
city exists in my dataframe. Here is the detailed code, I am able to see the background color of the row changed in the front-end, but the collapse/expand function is not work. 

`import dash
import pandas as pd
from app.pages.page_layout import layout
import dash_mantine_components as dmc
from dash import Input, Output,callback,dcc
from dash_iconify import DashIconify
import dash
from app import app
import dash_ag_grid as dag


dash.register_page(
    __name__

)

page_name = 'City'
df = pd.read_csv("/Users/hwang5/Downloads/country.csv",delimiter=';')


def getcolDef(df):
    df_columnDefs = []
    for i in df.columns:
        if i == 'Region':
            df_columnDefs.append({
            "headerName":'Region',
            "minWidth": 250,
            "pinned":"left",
            "showRowGroup": i,
            "cellRenderer": 'agGroupCellRenderer',
            "cellRendererParams": {
                "suppressCount": True},
            })
            df_columnDefs.append({"headerName": "Region", "field": i, "rowGroup": True, "hide": True, })
        elif i == 'Country':
            df_columnDefs.append({
            "headerName":'Country',
            "minWidth": 150,
            "pinned":"left",
            "showRowGroup": i,
            "cellRenderer": 'agGroupCellRenderer',
            "valueGetter": '(params) => {if (params.data) {return params.data.i;}}',
            "cellRendererParams": {
                "suppressCount": True},
            })
            df_columnDefs.append({"headerName": "Country", "field": i, "rowGroup": True, "hide": True, })
        elif i == 'City':
            df_columnDefs.append({"headerName": "City", "field": i, "minWidth": 250, "pinned":"left","cellRenderer": 'agGroupCellRenderer',
            "cellRendererParams": {
                "innerRenderer": 'SimpleCellRenderer'},})
        else:
            df_columnDefs.append({"headerName": i, "field": i, "type": 'rightAligned',"valueFormatter": {"function": "Numberformat(params.value)"}})
   
    return df_columnDefs


columnDefs = []
columnDefs = getcolDef(df=df)

getRowStyle2 = {
    "styleConditions": [
        {
            "condition": "params.data.City == 'Hamburg'",
            "style": {"backgroundColor": "lavenderblush"},
        },
    ]
}

table_container = dag.AgGrid(
        id="update-rowdata-grid",
        enableEnterpriseModules=True,
        rowData=df.to_dict('records'),
        columnDefs=columnDefs,
        columnSizeOptions={"skipHeader":True},
        defaultColDef=dict(
            resizable=True,
            sortable=False,
            filter=False,
        ),
        getRowStyle=getRowStyle2,
#Bold the entire total row
        dashGridOptions=dict(
            groupDefaultExpanded=-1,
            groupDisplayType='custom',
            groupHideOpenParents = True
            ),
        className="ag-theme-alpine",
        
        style={"height": "100vh"}
    )



# use layout function from page_layout.py

layout = layout(page_name,table_container)`
[country.csv](https://github.com/plotly/dash-ag-grid/files/12337292/country.csv)
![Screenshot 2023-08-14 at 18 20 57](https://github.com/plotly/dash-ag-grid/assets/135717933/cfdce2c5-c3d0-44f9-b847-4fcfc1124e60)
