### ISSUE TITLE
[Feature request] Excel Export - Multiple Sheets

### ISSUE THREAD

**Issue by crystle443925** [plotly/dash-ag-grid#235]
Hi I am using ag grid enterprise version, I see there is a feature called "Excel Export - Multiple Sheets", I am wondering do we have this feature in dash ag grid as well? It is really appreciated if there are similar feature like this.

See reference link below: ag-grid.com/angular-data-grid/excel-export-multiple-sheets/

**Comment by AnnMarieW** [comment]
Hi @crystle443925 

This feature is available - it's just not documented yet. You can find an example of  exporting multiple sheets to Excel in this thread on the forum:  https://community.plotly.com/t/dash-ag-grid-export-data-as-excel/77325

**Comment by crystle443925** [comment]
do you have any example of exporting multi grids to multiple sheets in one excel file?  Many thanks

**Comment by AnnMarieW** [comment]
@crystle443925 
Please ask how-to questions on the forum.  It's a best practice to keep the GitHub issues for things like feature requests and bugs reports.

**Comment by crystle443925** [comment]
Thanks for reminding. Let me ask the question in another way: Does dash grid has feature to export different grids into different sheet in one excel. I see this feature is documented in AG Grid, if it does, can you please tell me how to implement this feature? Any examples will be really appreciated
