### ISSUE TITLE
Add button that removes all filters

### ISSUE THREAD

**Issue by dwassner** [plotly/dash-ag-grid#239]
I have found that my end users struggle with removing filters from specific columns or all columns (having to manually delete the values in each field of each filter).

It would be really nice to have a button that removes all filtering from all columns.

Taking it a step further, if it were possible to have a button (possibly within the top section of the grid where the floating filters are) that would allow clearing filters for just tha column, that would be great as well.

Thank you.

**Comment by BSd3v** [comment]
Hello @dwassner,

You can do this via a dash callback. You are in control of the filterModel prop which you can use to clear the filters of the whole thing or just a column.

**Comment by AnnMarieW** [comment]
@dwassner 

Also, see the docs for how to add a [apply, clear, reset and cancel buttons](https://dash.plotly.com/dash-ag-grid/column-filters#apply,-clear,-reset-and-cancel-buttons) to the filters :slightly_smiling_face:

**Comment by BSd3v** [comment]
Closing this as this isnt in scope of creating a wrapper for AG Grid
