### ISSUE TITLE
csvExportParams skipRowGroups only works partially

### ISSUE THREAD

**Issue by johnkangw** [plotly/dash-ag-grid#240]
When using the skipRowGroups params as true, it does skip most row groups but keeps the grouped row summed value. The intended behavior would be to skip the entire row group (including the summed value). This is using dash-ag-grid 2.3.0 and dash 2.13.0. 

![image](https://github.com/plotly/dash-ag-grid/assets/72617548/d272515f-2867-4e79-9b3b-2f892ed5a39a)

**Comment by BSd3v** [comment]
Hello @johnkangw,

Assuming you are exporting this via the enterprise module, vs a callback, you need to pass this argument to the `defaultCsvExportParams` in the `dashGridOptions`.

Please find the below example:

```
import dash_ag_grid as dag
from dash import Dash, html, dcc
import pandas as pd
import os


app = Dash(__name__)


df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/ag-grid/olympic-winners.csv"
)

columnDefs = [
    # Row group by country and by year is enabled.
    {"field": "country", "sortable": True, "filter": True, "rowGroup": True},
    {"field": "year", "sortable": True, "filter": True, "rowGroup": True},
    {"field": "athlete", "sortable": True, "filter": True},
    {"field": "age", "sortable": True, "filter": True},
    {"field": "date", "sortable": True, "filter": True},
    {"field": "sport", "sortable": True, "filter": True},
    {"field": "total", "sortable": True, "filter": True},
]

app.layout = html.Div(
    [
        dcc.Markdown("Demonstration of row groupings in a Dash AG Grid."),
        dcc.Markdown("This grid groups first by country and then by year."),
        html.Button(id='export', children='Export to CSV'),
        dag.AgGrid(
            columnDefs=columnDefs,
            rowData=df.to_dict("records"),
            dashGridOptions={"rowSelection": "multiple",
                             "defaultCsvExportParams": {'skipRowGroups': True}},
            defaultColDef=dict(
                resizable=True,
            ),
            csvExportParams={'skipRowGroups': True},
            id="grouped-grid",
            enableEnterpriseModules=True,
        ),
    ]
)


if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by johnkangw** [comment]
@BSd3v Thanks for letting me know that I also need to set the DashGridOptions. I put it and similarly removed most of the grouping but kept one layer of groupings. Is it because I have an aggFunc setup in the columnDefs? 

csv_export_params = {
    'allColumns': True,
    'onlySelected': False,
    'skipColumnGroupHeaders': True,
    'skipRowGroups': True,
    'skipPinnedTop': True,
    'skipPinnedBottom': True,
}

![image](https://github.com/plotly/dash-ag-grid/assets/72617548/7c2f230a-dd1c-4bae-a8fe-ccb7f19719ed)

**Comment by BSd3v** [comment]
You dont also have to place it there, it just pertains to if you are going to be exporting via the grid's interface.

And most likely, is that issue.

You can use the api to make adjustments to how the grid is exporting, check here:

https://www.ag-grid.com/react-data-grid/csv-export/#grid-properties

You can use `shouldRowBeSkipped`

**Comment by johnkangw** [comment]
@BSd3v Thanks for the heads up! I tried using a function in shouldRowBeSkipped, but it did not work. I tried using the log(params) functionality, but it does not log anything. Do you know if shouldRowBeSkipped is implemented on the Dash side? 

# Setup DAG csvexportparams
csv_export_params = {
    'allColumns': True,
    'onlySelected': False,
    'skipColumnGroupHeaders': True,
    'skipRowGroups': True,
    'skipPinnedTop': True,
    'skipPinnedBottom': True,
    'shouldRowBeSkipped': {"function": "log(params)"}
    # 'shouldRowBeSkipped': {"function": "params.data ? params.data.n ame === null : false"},
}

**Comment by johnkangw** [comment]
@BSd3v Thanks so much for the heads up. I tried using the shouldRowBeSkipped parameter with a function, but it did not work. I tried logging, but nothing is showing up in the console. Is that parameter implemented on the Dash side? 
'shouldRowBeSkipped': {"function": "log(params)"}
![image](https://github.com/plotly/dash-ag-grid/assets/72617548/c16047f5-5db1-41e7-b7cc-ace270cea15c)

**Comment by BSd3v** [comment]
`shouldRowBeSkipped` is not currently setup in dash-ag-grid, and would need to be added.

You can however use the grid's api to adjust this.

**Comment by BSd3v** [comment]
I just tried with this example here:

https://dash.plotly.com/dash-ag-grid/enterprise-aggregation-custom-functions

```
import dash
from dash import Dash, html, dcc
import dash_ag_grid as dag
import pandas as pd
import os

app = Dash(__name__)

df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/ag-grid/olympic-winners.csv"
)

columnDefs = [
    # Row group by country and by year is enabled.
    {
        "field": "country",
        "rowGroup": True,
        "hide": True,
        "suppressColumnsToolPanel": True,
    },
    {
        "field": "sport",
        "rowGroup": True,
        "hide": True,
        "suppressColumnsToolPanel": True,
    },
    {
        "field": "year",
        "pivot": True,
        "hide": True,
        "suppressColumnsToolPanel": True,
    },
    {"field": "gold", "sortable": True, "filter": True, "aggFunc": "sum"},
    {"field": "silver", "sortable": True, "filter": True, "aggFunc": "sum"},
    {
        "headerName": "ratio",
        "colId": "goldSilverRatio",
        "aggFunc": {"function": "ratioAggFunc(params)"},
        "valueGetter": {"function": "ratioValueGetter(params)"},
        "valueFormatter": {"function": "ratioFormatter(params)"},
    },
]

app.layout = html.Div(
    [
        dcc.Markdown(
            "This is an example of how to calculate a ratio using values from multiple columns."
        ),
        dag.AgGrid(
            id="enterprise-aggregation-example-custom",
            enableEnterpriseModules=True,
            columnDefs=columnDefs,
            rowData=df.to_dict("records"),
            defaultColDef={"resizable":True},
            dashGridOptions={
                "rowSelection": "multiple",
                "suppressAggFuncInHeader": True,
                "defaultCsvExportParams": {"skipRowGroups": True}
            }
        ),
    ]
)


if __name__ == "__main__":
    app.run(debug=True)
```

No issue with skipping the grouped rows... Would be nice to see your raw data or something that you are using.

**Comment by johnkangw** [comment]
@BSd3v Thanks so much for bearing with me! I found what it was! I had groupIncludeFooter set as True, which included that group when I exported to CSV! When I set it to False, it works with no groups present! Thanks so much!

 dashGridOptions={
                "suppressAggFuncInHeader": True,
                "columnHoverHighlight": True,
                # TODO: Do not include 
                "groupIncludeFooter": False,
                # "groupIncludeFooter": True,
                "paginateChildRows": True,
                "groupRowRenderer": "agGroupCellRenderer",
                "skipHeaderOnAutoSize": True,
                "sideBar": sidebar_default,
                "defaultCsvExportParams": csv_export_params
            },

**Comment by BSd3v** [comment]
Glad you got it figured out.

**Comment by johnkangw** [comment]
Do you mind if I add an issue asking for the shouldRowBeSkipped parameter to be added to the library?

**Comment by BSd3v** [comment]
You can go ahead, it needs to be allowed to be a function.
