### ISSUE TITLE
add Range Selection

### ISSUE THREAD

**Issue by TaabuLaR** [plotly/dash-ag-grid#242]
Hello, I found a feature that would be very useful for me https://www.ag-grid.com/javascript-data-grid/range-selection/.
But I did not find any description of this feature in the documentation, and when I use it in my code via “enableRangeSelection=True”, an exception occurs about the absence of such a parameter.
Found some answer that says to enable "enableEnterpriseModules=True" https://community.plotly.com/t/does-dash-ag-grid-come-with-range-selection/75890.
But it did not help.
Thank you in advance for your cooperation.

**Comment by BSd3v** [comment]
Hello @TaabuLaR,

Did you try placing this inside of `dashGridOptions`? There are too many options in the grid to plague the whole first layer with these things.

**Comment by TaabuLaR** [comment]
Oh, thank you very much, didn't think of that. Everything worked, you saved my tomorrow's report :)
