### ISSUE TITLE
Possible to access data rendered in Pivot table?

### ISSUE THREAD

**Issue by liammcknight95** [plotly/dash-ag-grid#251]
When using selectedRows on a pivoted ag-grid table, you get no info if it's a grouped value.

cellClicked also only gives information regarding the rendered data also, but this doesn't map to a field in the virtualRowData - am I missing a field/parameter that would allow to access this data?

**Comment by BSd3v** [comment]
Hello @liammcknight95,

Could you please provide an example app for us to test?

**Comment by liammcknight95** [comment]
hi @BSd3v - I think what I'm actually looking for is the rowClicked property to be added on further inspection?

**Comment by BSd3v** [comment]
Hello @liammcknight95 ,

You can access the grids api and configure your own event listener for the rowClicked event. This way you configure it any way that you want to.
