### ISSUE TITLE
Retirement plan for pythonanywhere docs?

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-ag-grid#252]
Is it time to take the next step toward retiring the pythonanywhere docs? @danton267 pointed out to me that they're still on par with the official docs in Google searches. So they're presumably still getting a good deal of traffic. The banner telling people to switch is great, but it's still an extra step and doesn't take people to the specific page they want.

So it seems to me either we want to turn this site into a page-by-page redirect to the closest analogous page on the official docs, or if we want to keep these docs up, at least update the banner with page-by-page links.

@AnnMarieW thoughts?

**Comment by AnnMarieW** [comment]
I agree it's time to do a page-by-page redirect.  I can take on this project if you like.

About 20% of the content is not yet in the dash-docs.  How would you like to handle these cases?  It would be best to move it to the dash-docs,  but in the meantime, I could turn them into forum posts.   

I think one of the reasons the pythonanywhere links look popular is all the back links from the forum.  It would be great to update the forum links too, but I don't know if there is an easy way to do this.  I've asked Adam about it in the past.

**Comment by alexcjohnson** [comment]
OK great, yes please go ahead with creating redirects 🙇 
@LiamConnors pointed out this tracking issue for content that still needs adding to dash.plotly.com: https://github.com/plotly/ddk-dash-docs/issues/1589 - we'll try to prioritize that, and if as you go through the redirects you find any others we're missing please add them to that issue.

If we add the redirects, at least forum links will get folks to the main page, and hopefully Google will notice the redirects and reweight their results accordingly. But you're right that ideally we should try to replace those forum links - I mentioned this again to Adam, I'll leave the details up to you two, but if we have a concise list of redirects that will also make it easier to update the forum.

**Comment by AnnMarieW** [comment]
@alexcjohnson The redirects are live now.    Try this page for an example:  

https://dash.plotly.com/dash-ag-grid/column-sizing

This app now is small enough  that it can be hosted for free.  After it's merged, I'll remove credit card info for the Pythonanywere account and give you the password.
