### ISSUE TITLE
Allow conditionals in valueFormatter parameter

### ISSUE THREAD

**Issue by johnkangw** [plotly/dash-ag-grid#26]
The valueFormatter parameter for column definition is excellent but could be better if it allowed conditionals. For instance, I am setting a percentage format for the value in the below code. Therefore, I want to add a conditional that applies that format as long as value*100 is not NaN. If NaN, then use another function. 

`"valueFormatter": "Number(value*100).toFixed(0) + '%'",`

**Comment by johnkangw** [comment]
@BSd3v Thanks so much for the heads up. I'll have to read more into the documentation on how to use the cellRenderer. 

Do you know if there are any examples of how to set up a custom function for valueFormatter? I want to ensure that I am inputting and outputting the correct data.

**Comment by BSd3v** [comment]
There isnt a current example in the documents (we are working on that), but here is how it works:

assets/customScripts.js
```
var dagfuncs = window.dashAgGridFunctions = window.dashAgGridFunctions || {};
dagfuncs.Round = function(v, a=2) {
    return Math.round(v * (10**a)) / (10**a)
}
```

Then in the `columnDefs`, you call the function like this:
```"valueFormatter":{"function":"Round(value)"}```

**Comment by johnkangw** [comment]
@BSd3v Thanks for the explanation.

Can you provide me with some help? I tried what you wrote above, but I need help getting it to work. I apologize if I missed something obvious; I am unfamiliar with javascript. 

1. I created a customScripts.js in the assets folder with the below code:
```
var dagfuncs = window.dashAgGridFunctions = window.dashAgGridFunctions || {};
dagfuncs.Round = function(v, a=0.1) {
    return Math.round(v * (10**a)) / (10**a)
}

dagfuncs.Percentage = function(v) {
    return Math.Round(v * 100) + '%'
}
```

2. In the column definition dictionary, I have the below code, and the first valueFormatter works (not using a custom JS function), but I need help getting the other two using the custom-defined functions to work. 
```
                {
                    "field": "Mech Techs",
                    "columnGroupShow": "open",
                    "headerTooltip": tooltip_mech_staffing["description"],
                    "headerName": "Mech Techs",
                    "valueFormatter": "Number(value*100).toFixed(0) + '%'",
                    "dangerously_allow_html": True,
                },
                {
                    "field": "Mech Shifts Needed",
                    "columnGroupShow": "open",
                    "headerTooltip": tooltip_mech_equipment["description"],
                    "headerName": "Mech Shifts Needed",
                    "valueFormatter": {"function": "Round(value)"},
                },
                {
                    "field": "Body Techs",
                    "columnGroupShow": "open",
                    "headerTooltip": tooltip_body_staffing["description"],
                    "headerName": "Body Techs",
                    "valueFormatter": {"function": "Percentage(value)"},
                    "dangerously_allow_html": True,
                },
```

**Comment by BSd3v** [comment]
Until the new version is released, which is what the PR that was merged today, you can access the functions via:

`"valueFormatterFunction":"Percentage(value)"`, I believe.

**Comment by johnkangw** [comment]
@BSd3v Wow, thanks so much! Got it working!!! Yay. 

Also, I had to modify the percentage function to get it working. Below is the code. Thanks again for the help! 

```
dagfuncs.Percentage = function(v) {
    if (isNaN(Math.round(v))){
        return ''
    }
    return Math.round(v*100) + '%'
}
```

**Comment by BSd3v** [comment]
You're welcome, keep in mind, in the next release it will be as I previously formatted it above.

I wanted to remove the need for extra props. 😄

**Comment by johnkangw** [comment]
@BSd3v Will do! I'll make sure to update once the next release is out! Thanks!

**Comment by BSd3v** [comment]
Hello @johnkangw,

a2 is available now, there is a slight change from what I gave before. It will look like this instead:

`"valueFormatter":{"function":"Round(params.value)"}` to be able to use the same function.

We are allowing for the params to be passed in as the complete object, instead of splitting it part into the different objects. This allows for a closer match to the AG Grid docs for functions, etc.

**Comment by johnkangw** [comment]
@BSd3v Thanks for the reply! I'll download a2 next week and update the "valueFormatter" parameter. I appreciate the heads up for the change. I appreciate your work building this library!

**Comment by johnkangw** [comment]
@BSd3v Thanks for the update! I can confirm that what you mentioned works. 

Also, I needed to add "params" before all of the "value" and "colDef.headerName" arguments. Thanks for working hard on these changes and keeping me informed!
