### ISSUE TITLE
How To Pass a JavaScript Function to rowStyle or getRowStyles Property

### ISSUE THREAD

**Issue by quecksilberio** [plotly/dash-ag-grid#264]
Is it possible to somehow pass a JavaScript function to the rowStyle or getRowStyles attribute, similarily to the way I can pass a JavaScript function to the cellStyle attribute?

I'm trying to dynamically update the row styles based on the data in that row and I cannot use the styleConditions mechanism since the rowStyle is a continuous function of my row data.

I'm trying to achieve something of the likes:

`dag.AgGrid(rowStyle={'function': 'getMyRowStyle(params)'})`

I'm trying to dynamically set the css background property of the rows like in the image attached. I currenty solved it by updating the individual cell styles but it is a lot more complex and very problematic when feeding the grid live data since only the cells that change redraw. This is why I'm trying to find a solution using the row styles instead of the cell styles.

<img width="321" alt="Screenshot 2024-01-22 at 21 21 19" src="https://github.com/plotly/dash-ag-grid/assets/125982831/3b2f2262-5109-4e27-a00c-60fdd7512e68">

**Comment by BSd3v** [comment]
Hello @quecksilberio,

This should be available using the `getRowStyle`, `rowStyle` is for static assignment.

**Comment by AnnMarieW** [comment]
@quecksilberio - If you haven't solved this, please feel free to post your question on the Dash community forum and include a minimal example to show what you've tried so far.  Here's a related [post](https://community.plotly.com/t/compare-values-between-columns-and-change-color/77910) you might find helpful.
