### ISSUE TITLE
Full text search in agRichSelectCellEditor

### ISSUE THREAD

**Issue by Saxamos** [plotly/dash-ag-grid#269]
Hello,

Is it possible to use the text search feature available in ag grid [here](https://www.ag-grid.com/javascript-data-grid/provided-cell-editors-rich-select/#allow-typing)?

I can't manage to use it, here is my code:
```
        {
            "headerName": "My col",
            "field": "my_col",
            "cellEditor": "agRichSelectCellEditor",
            "cellEditorPopup": True,
            "cellEditorParams": {
                "values": ['toto', 'tata'],
                "searchType": 'match',
                "allowTyping": True,
                "filterList": True,
                "highlightMatch": True,
                "valueListMaxHeight": 220
            },
        },
```

It doesn't allow to write anything like in the example though.

Thank you,
Sam

**Comment by BSd3v** [comment]
Hello @Saxamos,

Just to verify, you are using AG Grid Enterprise?

**Comment by Saxamos** [comment]
Hello :)
Yes I am with a license.

**Comment by AnnMarieW** [comment]
Hi @Saxamos 

Yes, this is available in dash-ag-grid V31.  You can find an example on the forum here:
https://community.plotly.com/t/ag-grid-enterprise-rich-cell-select-editor/82356
