### ISSUE TITLE
API flashCell, getDisplayedRowAtIndex

### ISSUE THREAD

**Issue by ducnva** [plotly/dash-ag-grid#272]
Hi everyone,
I am new to using dash-ag-grid. Can someone show me how to call the flashCell and getDisplayedRowAtIndex APIs of ag-grid in dash-ag-grid?

**Comment by AnnMarieW** [comment]
Hi @ducnva 

Great question!  This isn't in the Dash docs yet, but I just posted a [tutorial on Dash Community Forum](https://community.plotly.com/t/how-to-use-the-ag-grid-api-with-dash/82582) which includes the answer.

If you have follow up questions or comments, please ask them on the forum.  We like to keep GitHub issues for feature requests and bug reports, so I'm going to close this issue now.
