### ISSUE TITLE
[BUG] "Invalid Number" shows up in dash ag grid after row transaction transiently for no reason

### ISSUE THREAD

**Issue by yxc8** [plotly/dash-ag-grid#277]
As described in the title, I haven't been able to find code that consistently reproduces this, but I want to throw this up there in case anyone have any insight. The column's cell I'm getting "Invalid Number" show up on the front end is not even supposed to be a number and the value itself is also not a number but a string, but this error shows up transiently from time to time and refreshing the app's page seems to make this front end bug disappear. I can't wrap my head around what might be causing this, so I appreciate any insight. Thank you!

**Comment by yxc8** [comment]
Follow up: This seems to happen consistently with json strings coming from json.dumps()

**Comment by BSd3v** [comment]
This sounds more than likely an issue with the inferred cellDataTypes on v31. You can disabled or set the offending columnDef `cellDataType` to string.

**Comment by yxc8** [comment]
@BSd3v Thank you for the quick response! Setting to **text** or **string** solved my problem. Reference for those with similar issue: https://dash.plotly.com/dash-ag-grid/cell-data-types
