### ISSUE TITLE
Registering custom aggFunc(s) to grid not working

### ISSUE THREAD

**Issue by DavidBord** [plotly/dash-ag-grid#278]
On propCategories.js aggFuncs is defined under GRID_MAYBE_FUNCTIONS where it assumed it is only a function but it is a dict where function names are the keys and functions are the values. Perhaps it should be defined under OBJ_OF_FUNCTIONS or a new category for OBJ_OF_MAYBE_FUNCTIONS?

**Comment by BSd3v** [comment]
Can you please provide an example of how you are proposing it should work?

We use this type of function in one other place, where it can be an object or a function.

**Comment by DavidBord** [comment]
Looking at the example from the [documentation](https://dash.plotly.com/dash-ag-grid/enterprise-aggregation-custom-functions), I would expect that if I set:
`aggFuncs={"function": "ratioAggFunc(params)"}`
And enable the sidebar with:
`sidebar=True`
Then when grouping I could replace one of the built-in agg funcs (sum, max etc) with ratioAggFunc but it is not available.

**Comment by BSd3v** [comment]
If you pass it like this:
```
aggFuncs={"function": "ratioAggFunc(params)"}
```

It is expecting you to return an object from the function as a map of the associated functions.

```
aggFuncs={"function": "customAggFuncs"}

dagFuncs.customAggFuncts = () => {
    return {
    "ratioAggFunc": "ratioAggFunc"
    }
}
```

Let me know if this works.

The other way I am looking at is this:
```
'aggFuncs': {'ratioAggFunc': {"function": "ratioAggFunc"}}
```

**Comment by DavidBord** [comment]
This does not work.
