### ISSUE TITLE
Issues from #281

### ISSUE THREAD

**Issue by BSd3v** [plotly/dash-ag-grid#285]
> @AnnMarieW 
> One more minor (and unrelated) item I found when I was updating the docs recently:
> 
> Console msg:
> 
> > ag-grid-community.auto.esm.js:484 AG Grid: setDatasource is deprecated. Please use 'api.setGridOption('datasource', newValue)' or 'api.updateGridOptions({ datasource: newValue })' instead.
> 
> https://github.com/plotly/dash-ag-grid/blob/97b4830a34a7e493e25ced31ca841a174b0df3ac/src/lib/fragments/AgGrid.react.js#L913
> 
> Do you think you could include this small update in this PR?

> @ndrezn 
> I am seeing:
> 
> ```
> tests/test_cell_data_type_override.py::test_cd001_cell_data_types_override FAILED                      [  5%]
> 
> E           selenium.common.exceptions.TimeoutException: Message: text -> 17/01/2024 not found within 10s, found: 04/02/11720
> ```
> 
> and:
> 
> ```
> tests/test_popupparent.py::test_pp001_popupParent FAILED                                               [ 60%]
> 
> E       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"body > .ag-popup .mantine-Select-input"}
> ```
> 
> failing locally but I believe this is unrelated to this PR.

**Comment by ndrezn** [comment]
Closing this because I think it was just a flakey local failure.
