### ISSUE TITLE
BUG - `enableGroupEdit` not working as expected

### ISSUE THREAD

**Issue by alexshoe** [plotly/dash-ag-grid#310]
- Setting `enableGroupEdit` to `True` in `dashGridOptions`should enable the editing of columns for an entire row group. However, when testing this out, it seems to only change the value of the cell at the top level of the row group but not apply to the rest of the group.

For example, in this screen recording, I would expect that my selection of "Item 1" in the "Item" column would then apply to all rows in that row group. The same would go for setting "12" in the "Value" column.

https://github.com/user-attachments/assets/0c79065a-763f-4afa-bf54-999391197796

Here is the minimal app that I used to test this:
```python
import dash
import dash_ag_grid as dag
import pandas as pd
from dash import html

app = dash.Dash(__name__)

# Sample data
data = {
    "Category": ["A", "A", "A", "B", "B", "B"],
    "Item": ["Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6"],
    "Value": [10, 20, 30, 40, 50, 60],
}

df = pd.DataFrame(data)

# Column definitions
column_defs = [
    {
        "headerName": "Category",
        "field": "Category",
        "rowGroup": True,
    },
    {
        "headerName": "Item",
        "field": "Item",
        "editable": True,
        "cellEditorParams": {"values": ["Item 1", "Item 2", "Item 3"]},
        "cellEditor": "agSelectCellEditor",
    },
    {
        "headerName": "Value",
        "field": "Value",
        "editable": True,
    },
]

# Grid options
grid_options = {
    "columnDefs": column_defs,
    "defaultColDef": {
        "resizable": True,
        "sortable": True,
    },
    "groupDisplayType": "multipleColumns",
    "enableGroupEdit": True,  # Enable editing for group rows
}

app.layout = html.Div(
    [
        dag.AgGrid(
            id="grid",
            rowData=df.to_dict("records"),
            columnDefs=column_defs,
            dashGridOptions=grid_options,
            enableEnterpriseModules=True,
        )
    ]
)

if __name__ == "__main__":
    app.run_server(debug=True)

```

**Comment by BSd3v** [comment]
Hello @alexshoe,

Dont think this is a bug, you have to manually update the data, there isnt even documentation on how this works exactly. Check here:

https://stackoverflow.com/questions/64151825/editable-group-cell-in-ag-grid

Basically, you have to handle the updating your self based upon an event listener.

```
onCellEditingStopped={(e) => {
    const { newValue, node, api } = e;
    if (node.group) {
      node.groupData["ag-Grid-AutoColumn"] = newValue;
      api.refreshCells({
        force: true,
        rowNodes: [node]
      });
    }
  }}
```

I'm not even entirely sure what the benefit of the `enableGroupEdit` is... Except maybe being able to push data across the whole thing... Anyways, you need to adjust this yourself.

We can continue discussion of this on the forums. 😄

**Comment by alexshoe** [comment]
@BSd3v ah ok, thanks for clarifying!
