### ISSUE TITLE
Is it possible to override the Aggrid Version?

### ISSUE THREAD

**Issue by leijer** [plotly/dash-ag-grid#320]
I want to use the grand total row in Aggrid 31.3.0

https://blog.ag-grid.com/whats-new-in-ag-grid-31-3/
https://www.ag-grid.com/react-data-grid/total-rows/?ref=blog.ag-grid.com

Is there a way I can replace the aggrid javascript reference somehow on dash-ag-grid 31.2.0 so that it points to the new aggrid javascript library?

I know there's the potential for breaking changes but in this case i think unlikely as it is just a property on dashGridOptions

dashGridOptions = { "grandTotalRow": "top" }

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson

**Comment by AnnMarieW** [comment]
@leijer It's currently not possible to specify a different AG Grid version with dash-ag-grid.  It will be necessary to wait for the next release.
