### ISSUE TITLE
Could you also implement getColumnGroupState and setColumnGroupState in dash ag grid? 

### ISSUE THREAD

**Issue by littlefishna** [plotly/dash-ag-grid#322]
https://www.ag-grid.com/javascript-data-grid/column-state/#column-group-state

**Comment by BSd3v** [comment]
Hello @littlefishna,

You are able to access this by utilizing the grid's api. :)

**Comment by littlefishna** [comment]
Hi @BSd3v , thanks for responding. How may I do so? Thanks

**Comment by AnnMarieW** [comment]
@littlefishna could you say more about what you are looking for?  If it's just to have column groups that can expand, did you see this example in the docs?  https://dash.plotly.com/dash-ag-grid/column-groups

**Comment by littlefishna** [comment]
> @littlefishna could you say more about what you are looking for? If it's just to have column groups that can expand, did you see this example in the docs? https://dash.plotly.com/dash-ag-grid/column-groups

Hi @AnnMarieW, thanks for asking. My main use case is that i would like to persist column group state as well for individual users. Probably i will save column group state on client side. Not sure if you have any better ideas?

**Comment by AnnMarieW** [comment]
Hi @littlefishna  - yes, saving the column state is probably the best solution.  I expect that you saw all the examples here: https://dash.plotly.com/dash-ag-grid/column-state
