### ISSUE TITLE
Issue with dash_ag_grid not found in version 31.3.0

### ISSUE THREAD

**Issue by dmoccia** [plotly/dash-ag-grid#345]
Hello-

Just flagging this as I encountered a "Error: dash_ag_grid was not found" in my application when updating from 31.2.0 to the latest 31.3.0.  This particular application is embedded in django via django-plotly-dash and the result of the update was that no ag grid table was present (the plotly dash app appeared blanked out).  This could be an issue with DPD as well though my version of that did not change and remains fixed at 2.3.2, plotly 5.24.1.   Obviously the error message is pretty minimal and I see no issues on the django side.  

I rolled back to the previous version of dash-ag-grid and my app is working as expected but not sure if the new version has something that might be causing this issue such as a missing/renamed js?

Happy to provide more detail or help in the troubleshooting if this issue is encountered by others.   

Thanks!

**Comment by gvwilson** [comment]
@BSd3v have you run into this at all?

**Comment by BSd3v** [comment]
No, I havent run into this before. However, if there is something that AG Grid is dependent upon in Dash and django plotly dash is not updated, then it would break.

Did you check to make sure that it installed correctly?

**Comment by dmoccia** [comment]
The installation appeared to go fine as I checked which version was installed once I hit the error in the browser.  I suppose it could have failed silently but I believe Docker would have complained about it.   I will try rebuilding with the 31.3.0 version to be sure.   You make a good point on dependencies @BSd3v, I do wonder if there is an issue with the older version of DPD.  Might be a couple of days before I can check this out but will report back.

**Comment by yang-ruoxi** [comment]
I have encountered the same issue after upgrading to `31.3.0`. I am using `dash_ag_grid` and when I try to deploy our App, I get the `dash_ag_grid was not found` error. When inspecting the network I got:

![Image](https://github.com/user-attachments/assets/a52abb4f-2c1f-44e3-be21-684bdfaf714e)

Seems like a CDN error?

**Comment by BSd3v** [comment]
@ndrezn have you seen this before?

**Comment by alexcjohnson** [comment]
We need to publish to NPM with every release. These users must set `serve_locally=False`. https://www.npmjs.com/package/dash-ag-grid Is still showing 31.2.0 as the latest.

**Comment by ndrezn** [comment]
Published to NPM: https://www.npmjs.com/package/dash-ag-grid/v/31.3.0
