### ISSUE TITLE
empty grid "Loading..." overlay interferes with date picker dropdown

### ISSUE THREAD

**Issue by scott-sattler** [plotly/dash-ag-grid#350]
Grids with `columnDefs`, but without `rowData`, are rendered with a "Loading..." overlay.
This overlay both improperly obscures and prevents interaction with `dcc.DatePickerRange()`.
This may also occur with other components, but has not been tested.

- ~z-height appeared to have no effect~
- wrapping the ag-grid in another loading component (e.g. `dcc.Loading()`) appears to be a potential workaround (though I was unable to use this due to `target_components` not behaving as expected).

![Image](https://github.com/user-attachments/assets/2005c006-7a18-4078-ba09-2eb6a325e3dd)

![Image](https://github.com/user-attachments/assets/a07b1556-4c59-49d3-89e7-8ebabd147fb7)

# minimal reproducible example:
```python
from dash import Dash, html, dcc, Input, Output, callback

import dash_ag_grid as dag
import pandas as pd


columnDefs = [
    {'field': 'direction'},
    {'field': 'strength'},
    {'field': 'frequency'},
]

app = Dash()
app.layout = html.Div([
    dcc.DatePickerRange(id='my-date-picker-range'),
    dag.AgGrid(id="ag-grid", columnDefs=columnDefs, style={"margin-left": "10em"}),
    html.Button('click to see properly working display', id='btn', n_clicks=0),
])


@callback(
    Output('ag-grid', 'rowData'),
    Input('btn', 'n_clicks'),
    prevent_initial_call=True
)
def update_output(n_clicks):
    df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/wind_dataset.csv")
    return df.to_dict("records")


if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by AnnMarieW** [comment]
adding `zIndex` to the date picker worked for me

```
 dcc.DatePickerRange(id='my-date-picker-range', style={"zIndex": 100}),
```

**Comment by BSd3v** [comment]
The default order at which components are rendered is going to be the according to the DOM tree. The last placed component will be given priority. That's why the grid is overlaying the loading on top of the datePicker. 

The workaround is to add a zIndex as @AnnMarieW suggested.

**Comment by scott-sattler** [comment]
got it working. much appreciated
