### ISSUE TITLE
Conditional cellClass parameter analogous to cellStyle

### ISSUE THREAD

**Issue by mateusz-szczesny** [plotly/dash-ag-grid#41]
It would be nice to have functionality that reflects https://www.ag-grid.com/angular-data-grid/cell-styles/#cell-class

It might work similarly to already implemented conditional `cellStyle`.

**For Styles**
```python
cellStyle={
    "styleConditions": [
        {"condition": "value == 72000", "style": {"color": "orange"}},       
    ]
}
```

**For Classes**
```python
cellClass={
    "classConditions": [
        {"condition": "value == 72000", "class": "bg-dark bg-opacity-25"},       
    ]
}
```

**Comment by BSd3v** [comment]
Hello @mateusz-szczesny,

Currently, there is no need for `cellClass` to take on the same as `cellStyles`, `cellClassRules` can be used for that instance.

We are going to fix it so that `cellClassRules` can be used in a similar fashion to the `cellStyles` that you mentioned above.

**Comment by BSd3v** [comment]
We have this in this PR: https://github.com/plotly/dash-ag-grid/pull/49

`cellClassRules` will follow the same format as what is in AG-Grid docs. 

https://www.ag-grid.com/react-data-grid/cell-styles/#cell-class-rules
