### ISSUE TITLE
Markdown html links with `target="_blank` not opening in new tab

### ISSUE THREAD

**Issue by AnnMarieW** [plotly/dash-ag-grid#44]
As reported on the [forum](https://community.plotly.com/t/dash-ag-grid-open-source/72352/26?u=annmariew), In the Markdown component html links with `target="_blank` do not open in a new tab

**Comment by sylvoslee** [comment]
How do I update to the latest version, I need this feature now

**Comment by BSd3v** [comment]
Hello @sylvoslee,

there are other ways to open links in another tab, without using html. 

You can pass a linkTarget of “_blank” to the columnDef that you want the links to open, and any markdown link will have that target.

**Comment by sylvoslee** [comment]
> Hello @sylvoslee,
> 
> there are other ways to open links in another tab, without using html.
> 
> You can pass a linkTarget of “_blank” to the columnDef that you want the links to open, and any markdown link will have that target.

nice,thank you@BSd3v
