### ISSUE TITLE
demo stock portfolio app not working

### ISSUE THREAD

**Issue by haiwu** [plotly/dash-ag-grid#58]
It errors out with this message all the time when loading: 
`Invalid prop for this component`
`Property "selectedRows" was used with component ID:
  "portfolio-grid"
in one of the Input items of a callback.
This ID is assigned to a dash_ag_grid.AgGrid component
in the layout, which does not support this property.
This ID was used in the callback(s) for Output(s):
  candlestick.figure`
all relevant python packages for this demo app are with latest release already.

**Comment by BSd3v** [comment]
Hello @haiwu,

Make sure you are using version a2.

**Comment by haiwu** [comment]
Ah that's it! It is working now. Thank you!
