### ISSUE TITLE
Clearing rows of a grid with infinite row model

### ISSUE THREAD

**Issue by fvdnabee** [plotly/dash-ag-grid#59]
When rendering filtered data in an ag grid with the inifinite row model, the grid contains stale rows that ought to be removed when changing data filters. E.g. consider the following scenario:
* the grid contains ten rows loaded via infinite row model
* the user updates its data filters (the filters are other dash components)
* scrolling through the table, the grid still contains the previously loaded ten rows (some of which might no longer be matched by the new data filters)

I tried the naive approach of setting rowData to an empty list when the filter dash input changes:
```python
@app.callback(
    dash.dependencies.Output("data-grid", "rowData"),
    dash.dependencies.Input('data-filter', 'value'), 
)
def update_rowdata(*_):
    """Clear rowData when one of the filters change, otherwise the table contains stale rows."""
    if not dash.ctx.triggered_id:
        return dash.no_update  # If callback wasn't triggered by input, ignore.

    return []
```
But rowData isn't available for grids with `rowModelType='infinite'`. This callback throws the error (warning: long):

<details>
<summary>this.clientSideRowModel is undefined</summary>
<blockquote>
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)

7351/e.prototype.setRowData@http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:2:640824

7351/e.prototype.__setProperty@http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:2:637400

7351/e.processOnChange/<@http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:2:133335

7351/e.processOnChange@http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:2:133270

3920/t.prototype.processChanges/<@http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:2:1106407

3920/t.prototype.processWhenReady@http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:2:1106488

3920/t.prototype.processChanges@http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:2:1106355

3920/t.prototype.processPropsChanges@http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:2:1105835

3920/t.prototype.componentDidUpdate@http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:2:1105701

commitLifeCycles@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:19970:24

commitLayoutEffects@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:22938:25

callCallback@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:182:16

invokeGuardedCallbackDev@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:231:18

invokeGuardedCallback@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:286:33

commitRootImpl@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:22676:32

unstable_runWithPriority@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react@16.v2_8_1m1677594670.14.0.js:2685:14

runWithPriority$1@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:11174:12

commitRoot@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:22516:22

finishSyncRender@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:21942:15

performSyncWorkOnRoot@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:21928:25

flushSyncCallbackQueueImpl/<@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:11224:26

unstable_runWithPriority@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react@16.v2_8_1m1677594670.14.0.js:2685:14

runWithPriority$1@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:11174:12

flushSyncCallbackQueueImpl@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:11219:26

flushSyncCallbackQueue@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:11207:5

batchedUpdates$1@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:21997:9

notify@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:11550:12

notifyNestedSubs@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:11610:15

handleChangeWrapper@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:11614:20

dispatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:76043:7

./node_modules/redux-thunk/es/index.js/createThunkMiddleware/middleware/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:75713:16

applyProps@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1584:15

./src/observers/executedCallbacks.ts/observer/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1617:40

forEach@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:81428:7

./node_modules/ramda/es/internal/_checkForMethod.js/_checkForMethod/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83578:119

f2@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83834:14

./src/observers/executedCallbacks.ts/observer/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1607:55

forEach@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:81428:7

./node_modules/ramda/es/internal/_checkForMethod.js/_checkForMethod/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83578:119

f2@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83834:14

observer@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1593:51

./src/StoreObserver.ts/StoreObserver/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:355:9

forEach@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:81428:7

./node_modules/ramda/es/internal/_checkForMethod.js/_checkForMethod/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83578:119

f2@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83834:14

./src/StoreObserver.ts/StoreObserver/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:353:51

dispatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:76043:7

./node_modules/redux-thunk/es/index.js/createThunkMiddleware/middleware/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:75713:16

_callee$@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1823:25

tryCatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1760:2404

./src/observers/executingCallbacks.ts/_regeneratorRuntime/wrap/generator._invoke@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1760:1972

./src/observers/executingCallbacks.ts/_regeneratorRuntime/defineIteratorMethods/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1760:3255

asyncGeneratorStep@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1764:103

_next@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1765:212

promise callback*asyncGeneratorStep@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1764:242

_next@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1765:212

./src/observers/executingCallbacks.ts/_asyncToGenerator/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1765:369

./src/observers/executingCallbacks.ts/_asyncToGenerator/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1765:97

./src/observers/executingCallbacks.ts/observer/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1834:22

forEach@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:81428:7

./node_modules/ramda/es/internal/_checkForMethod.js/_checkForMethod/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83578:119

f2@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83834:14

observer@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1790:51

./src/StoreObserver.ts/StoreObserver/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:355:9

forEach@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:81428:7

./node_modules/ramda/es/internal/_checkForMethod.js/_checkForMethod/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83578:119

f2@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83834:14

./src/StoreObserver.ts/StoreObserver/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:353:51

dispatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:76043:7

./node_modules/redux-thunk/es/index.js/createThunkMiddleware/middleware/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:75713:16

_callee2$@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2036:25

tryCatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1959:2404

./src/observers/prioritizedCallbacks.ts/_regeneratorRuntime/wrap/generator._invoke@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1959:1972

./src/observers/prioritizedCallbacks.ts/_regeneratorRuntime/defineIteratorMethods/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1959:3255

asyncGeneratorStep@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1967:103

_next@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1968:212

./src/observers/prioritizedCallbacks.ts/_asyncToGenerator/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1968:369

./src/observers/prioritizedCallbacks.ts/_asyncToGenerator/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:1968:97

observer@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2092:24

./src/StoreObserver.ts/StoreObserver/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:355:9

forEach@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:81428:7

./node_modules/ramda/es/internal/_checkForMethod.js/_checkForMethod/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83578:119

f2@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83834:14

./src/StoreObserver.ts/StoreObserver/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:353:51

dispatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:76043:7

./node_modules/redux-thunk/es/index.js/createThunkMiddleware/middleware/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:75713:16

_callee$@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2330:23

tryCatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2116:2404

./src/observers/requestedCallbacks.ts/_regeneratorRuntime/wrap/generator._invoke@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2116:1972

./src/observers/requestedCallbacks.ts/_regeneratorRuntime/defineIteratorMethods/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2116:3255

asyncGeneratorStep@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2120:103

_next@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2121:212

promise callback*asyncGeneratorStep@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2120:242

_next@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2121:212

./src/observers/requestedCallbacks.ts/_asyncToGenerator/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2121:369

./src/observers/requestedCallbacks.ts/_asyncToGenerator/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2121:97

observer@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:2347:24

./src/StoreObserver.ts/StoreObserver/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:355:9

forEach@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:81428:7

./node_modules/ramda/es/internal/_checkForMethod.js/_checkForMethod/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83578:119

f2@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:83834:14

./src/StoreObserver.ts/StoreObserver/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:353:51

dispatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:76043:7

./node_modules/redux-thunk/es/index.js/createThunkMiddleware/middleware/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:75713:16

dispatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:76437:28

_callee$@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:5057:23

tryCatch@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:4946:2404

./src/actions/index.js/_regeneratorRuntime/wrap/generator._invoke@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:4946:1972

./src/actions/index.js/_regeneratorRuntime/defineIteratorMethods/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:4946:3255

asyncGeneratorStep@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:4947:103

_next@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:4948:212

./src/actions/index.js/_asyncToGenerator/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:4948:369

./src/actions/index.js/_asyncToGenerator/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:4948:97

./src/actions/index.js/notifyObservers/<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:5066:20

./node_modules/redux-thunk/es/index.js/createThunkMiddleware/middleware/</<@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:75709:18

setProps@http://127.0.0.1:8050/_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_8_1m1677594669.dev.js:3352:32

87781/B/C<@http://127.0.0.1:8050/_dash-component-suites/dash/dcc/async-dropdown.js:2:4256

value@http://127.0.0.1:8050/_dash-component-suites/dash/dcc/async-dropdown.js:2:30660

value@http://127.0.0.1:8050/_dash-component-suites/dash/dcc/async-dropdown.js:2:31433

11622/value/<@http://127.0.0.1:8050/_dash-component-suites/dash/dcc/async-dropdown.js:2:31098

callCallback@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_8_1m1677594670.14.0.js:12625:14
</blockquote>
</details>

The ag grid docs state under [Changing the Datasource](https://www.ag-grid.com/javascript-data-grid/infinite-scrolling/#changing-the-datasource):
> Changing the datasource after the grid is initialised will reset the infinite scrolling in the grid. This is useful if the context of your data changes, i.e. if you want to look at a different set of data.

If a dash callback could change the datasource of the grid, then the grid should reset its rows. However, setting the datasource from a dash callback  currently isn't supported by dash-ag-grid (afaik). Perhaps setting the datasource directly isn't required here, but a clear rows (or equivalent) dash output would be welcomed in dash-ag-grid. Maybe there are other ways to clear a grid with the infinite row model in dash-ag-grid?

As a tangent: the [dash-ag-grid docs](https://dashaggrid.pythonanywhere.com/enterprise/infinite-scroll) lists infinite scroll under Enterprise features, while the ag grid docs lists the infinite row model as [a community feature](https://www.ag-grid.com/javascript-data-grid/row-models/). Are the dash-ag-grid docs incorrect?

**Comment by BSd3v** [comment]
Hello @fvdnabee,

You are correct, infinite rows are not enterprise, only server side scrolling is.

We havent looked into changing data sources during run time, you can use some stuff with the `getRowsRequest` and changing, the source there. Issue is that it keeps your current scroll position, which you could probably get it to work somewhat. The dfs would have to be the same length, or it just stops updating.

An actual version to process this change would be good once the grid is loaded.

**Comment by fvdnabee** [comment]
This draft PR introduces a new property `clearInfiniteRows`: https://github.com/plotly/dash-ag-grid/pull/62.
From my (limited) testing the property enables the scenario from the OP with the following two callbacks (one to clear the rows and one for fetching the data):

```python
@app.callback(
    dash.dependencies.Output("data-grid", "clearInfiniteRows"),
    dash.dependencies.Input('filter', 'value'), 
)
def infinite_scroll_clear_rows(*_):
    """Clear the grid rows when one of the filters change, otherwise the table contains stale rows."""
    if not dash.ctx.triggered_id:
        return False  # If callbacks wasn't triggered by input, ignore.

    return True


@app.callback(
    dash.dependencies.Output("data-grid", "getRowsResponse"),
    dash.dependencies.Input("data-grid", "getRowsRequest"),
    dash.dependencies.Input('filter', 'value'), 
)
def infinite_scroll(row_request, filter):
    if row_request is None:
        return dash.no_update
    dff = filter_df(filter)

    partial = dff.iloc[row_request["startRow"] : row_request["endRow"]]
    return {"rowData": partial.to_dict("records"), "rowCount": len(dff.index)}
```

Changing the data source also resets the scroll position. When the filter input is changed, the grid's existing rows are deleted and then the getRowsRequest property populates the new rows for the new filter. I had some worries about concurrency issues (i.e. which callback would be called first); but it seems the clear callback happens consistently before the infinite_scroll callback.

**Comment by BSd3v** [comment]
Hmm, I dont know if I like this necessarily. Its dependent upon a chained callback. 

I think I have a different idea for this.

**Comment by BSd3v** [comment]
@fvdnabee, here is my proposed flow:
```
@app.callback(
    Output("grid1", "getRowsResponse"),
    Input("grid1", "getRowsRequest"),
    Input('new_data', 'n_clicks')
)
def infinite_scroll(request, n):
    if n:
        dff = dfSource[str(n%2)]
    else:
        dff = dfSource['0']

    if request is None:
        return no_update
    if ctx.triggered_id == 'new_data':
        return {"resetRows": True}

    partial = dff.iloc[request["startRow"]: request["endRow"]]
    return {"rowData": partial.to_dict("records"), "rowCount": len(dff.index)}
```

**Comment by fvdnabee** [comment]
The one callback looks cleaner than having two! :+1: 

In your example, shouldn't the `ctx.triggered_id == 'new_data'` if statement be placed before the `request is None` if statement though (as request is None when the callback is called when clicking the button)?

**Comment by BSd3v** [comment]
Technically, the request isn’t blank because it never gets cleared. 😁

**Comment by BSd3v** [comment]
Hello @fvdnabee,

This may actually get cleared up with our prop clean up.

**Comment by BSd3v** [comment]
I can actually confirm this. There are some caveats, you have to make sure that you never clear the grid completely with a 0 row count, you'll always have to put 1 if it equals 0. This helps keep the requests flowing in to the server.

**Comment by BSd3v** [comment]
There is a way to systematically reset the cache of infinite rows with 2.2+, check here for an example:

https://community.plotly.com/t/dash-ag-grid-infinite-row-model-updating-startrow-and-endrow/76487/14?u=jinnyzor
