### ISSUE TITLE
Row Spanning

### ISSUE THREAD

**Issue by Thuener** [plotly/dash-ag-grid#71]
I tried to use the RowSpan functionally form AGGrid but was not able to make it work.

Is the Row Spanning functionality from AGGrid working?
https://www.ag-grid.com/javascript-data-grid/row-spanning/

**Comment by AnnMarieW** [comment]
Hi @Thuener - This will be available in the next release :tada:

**Comment by AnnMarieW** [comment]
@Thuener 
The new release is out:
```
pip install dash-ag-grid==2.0.0a3
```
See an example in the docs here:  https://dashaggrid.pythonanywhere.com/rows/row-spanning

**Comment by Thuener** [comment]
Great. Thanks!
