### ISSUE TITLE
“Undefined” is not valid JSON (after upgrading dash-ag-grid)

### ISSUE THREAD

**Issue by esdesai** [plotly/dash-ag-grid#79]
Started receiving “Undefined is not valid JSON” after upgrading dash-ag-grid package from 2.0.0a1 to 2.0.0a3.  No code changes were made when upgrading.  AG Grid table no longer displays after the upgrade.

**Comment by alexcjohnson** [comment]
Can you share your code, or even better some pared down version that still shows the issue? There are some breaking changes between each alpha release so your code may not be expected to work without a change, but an error like that isn't very helpful so may point to a bug as well.

**Comment by esdesai** [comment]
Partial Code below

defaultColDef = {
    "resizable": True,
    #"initialWidth": 200,
    "wrapHeaderText": True,
    "autoHeaderHeight": True,
}

scorecard_table_overview_new = dbc.Card(
        children = [
            dag.AgGrid(
                id = 'scorecard-table',
                className="ag-theme-alpine-dark",
                columnSize="sizeToFit",
                dashGridOptions={"pagination": True, "paginationPageSize": 15 },
                defaultColDef=defaultColDef
                )
            ]
        )

@app.callback(
    [Output("scorecard-table", "columnDefs"),
    Output("scorecard-table", "rowData"),
    ],
    [Input("cto-filter", "value"),
    Input("scorecard-filter", "value")],
    )

def update_table_content(cto_name, scorecard_filter):
    if scorecard_filter == "monthlyscorecard":
        if cto_name == "ALL":
            scorecard_table = cto_scorecard_df.to_json(orient='records')
        else:
            scorecard_table = seal_scorecard_df[seal_scorecard_df['CTO'] == cto_name]
            scorecard_table.drop(columns=['CTO'], axis=1, inplace=True)
            scorecard_table.rename(columns={'App':'CTO'},inplace=True)
            scorecard_table = scorecard_table.to_json(orient='records')
			
        score_card_columns= [
            { "headerName": "Name", "field": "CTO",
                "valueFormatter": {"function": "(params.value).toUpperCase();", "dangerously_allow_html": True},
                },
            { "headerName": "Monthly Potential Savings", "field": "Monthly savings", "filter": "agNumberColumnFilter", "valueFormatter":"Number(value).toFixed(2)", "dangerously_allow_html": True},
            { "headerName": "Current Month", "field": "2023-02", "valueFormatter": {"function": "'$' + (params.value)", "dangerously_allow_html": True},},
            { "headerName": "Previous Month", "field": "2023-01"},
            { "headerName": "Delta", "field": "diff"},
            ]
			
	return [score_card_columns, json.loads(scorecard_table)]

**Comment by BSd3v** [comment]
Hello @esdesai,

Typically, you would use `scorecard_table.to_dict('records')` when sending `rowData` back to the table, no need to convert to JSON.

Could you please try this? Without data to test out, we cant very easily troubleshoot.

**Comment by esdesai** [comment]
Hi, I also tried to_dict(‘records’) and received the same error.

It seems like the issue is with setting the score_card_columns inside the app.callback.   If i hardcode the columns outside of the callback, I do not get the error with the latest version.     Please advise on how we can pass both Data & Columns within the callback.

**Comment by alexcjohnson** [comment]
Closing, this was an intentional change between a1 and a3, the safe evaluation functionality we added requires you to wrap `valueFormatter` in `{function: ...}` rather than just send the string, so that we know to parse it ourselves rather than send the string to AG Grid to parse dangerously.
