### ISSUE TITLE
Scrolling locks grid

### ISSUE THREAD

**Issue by danwbean** [plotly/dash-ag-grid#84]
With a single ag_grid in the layout (no callbacks) and about 300 records, scrolling the grid up and down with the mouse wheel for maybe 15 seconds causes the browser to become intermittent and finally die.  (repeatable in Chrome and Firefox).     

- Alpha version 2.0.0a2
- Dataframe is [318 rows x 15 columns]

Odd observation: It happens much faster if there is an external style_sheet (external_stylesheets=[dbc.themes.DARKLY]). With no stylesheet it still occurs, but take longer.

```
tbl = 'Site'

app = Dash(__name__, external_stylesheets=[dbc.themes.DARKLY])

table = dag.AgGrid(
            id='ag_grid',

            columnDefs=columnDefs,
            className='ag-theme-alpine-dark',
            rowData=df.to_dict('records'),
            columnSize='autoSizeAll',     # sizeToFit, autoSizeAll
            # cellStyle=cellStyle,      # would be used for conditional formatting (see demo-stock-portfolio.py)
            dashGridOptions={
                'undoRedoCellEditing': True,
                'rowSelection': 'single'
            },
            defaultColDef=dict(
                resizable=True,
                sortable=True,
                filter=True,
                floatingFilter=True
                ),
            )

header = html.Div(tbl + ' Data',
                  className='h2 p-2 text-white bg-primary text-center')

app.layout = dbc.Container(
    [
        header,
        dbc.Row(dbc.Col(table), className='py-4'),   
    ],
)
```

a typical columnDef:

```
 {
                'headerName': 'Smithsonian',
                'field': 'Smithsonian',
                'filter': 'agTextColumnFilter',
                'editable': False,
}
```

**Comment by AnnMarieW** [comment]
Hi @danwbean 

Could you please update to the latest version?
```
pip install dash-ag-grid==2.0.0a3
```

Also, could you please include some sample data because I can't replicate the error.

**Comment by danwbean** [comment]
Will do.  I hate intermittent behavior.  This morning I cannot get it to fail.  No changes, no restart.
If it does it again I will send a functioning version with a data set.
Thanks.  Great piece of software.

**Comment by AnnMarieW** [comment]
Ok, I'll close this for now, but please feel free to open a new issue if you can isolate the problem.
Glad you like dash-ag-grid :slightly_smiling_face:
