### ISSUE TITLE
Document accessing rowData in a callback in an editable grid

### ISSUE THREAD

**Issue by AnnMarieW** [plotly/dash-ag-grid#85]
As the user makes edits, the `cellValueChanged` is updated, but the `RowData` is not. 

The `rowData` also needs to be updated so that correct data is available for use in a callback.

**Comment by BSd3v** [comment]
This is due to the `rowData` being linked, it cannot be used to trigger inputs, but when you look at the state of the `rowData` when those events happen, the `rowData` reflects what is in the table.

Looking into a way to trigger the updates.

**Comment by alexcjohnson** [comment]
@AnnMarieW are you saying if you make a callback with both `cellValueChanged` and `rowData` as inputs, `rowData` is not yet updated when the callback fires? Can you give an example app? Is this about async updates perhaps?

Feels like `cellValueChanged` should be enough of a trigger, but another option could be alongside `cellValueChanged` to also do `setProps({rowData: [...rowData]})` so it's a new array. That might cause an infinite loop though, would need to try it.

**Comment by BSd3v** [comment]
I have some tests:

```
"""
Working with infinite scroll against a backend database in AG-Grid.
"""
import traceback

import dash_ag_grid as dag
from dash import Dash, Input, Output, html, no_update, State, ctx, dcc
import pandas as pd
import requests, json

app = Dash(__name__)

columnDefs = [
    {
        "headerName": "Make",
        "field": "make",
    },
    {
        "headerName": "Model",
        "field": "model",
    },
    {"headerName": "Price", "field": "price"}
]

rowData = [
    {"make": "Toyota", "model": "Celica", "price": 35000},
    {"make": "Ford", "model": "Mondeo", "price": 32000},
    {"make": "Porsche", "model": "Boxter", "price": 72000},
]

extraData = [
    {"make": "Subaru", "model": "Impreza", "price": 35000},
    {"make": "Mazda", "model": "CX-5", "price": 32000},
    {"make": "Honda", "model": "Pilot", "price": 72000},
]

defaultColDef = {"editable": True}

app.layout = html.Div(
    [
        dcc.Markdown(
            "In this grid, the __Make__ column has a popup below the cell,  the __Model__ has a popup above the cell, and the __Price__ has the default (in cell) editor."
        ),
        dag.AgGrid(
            columnDefs=columnDefs,
            rowData=rowData,
            defaultColDef=defaultColDef,
            columnSize="sizeToFit",
            id="grid",
        ),
        html.Div(id='data'),
        html.Button(id='reset', children='reset', n_clicks=0),
        html.Button('addRow', id='addRow', n_clicks=0),
        html.Button('addRow_notAsync', id='addRow_notAsync', n_clicks=0)
    ],
    style={"margin": 20},
)

@app.callback(Output('data', 'children'), Input('grid', 'cellValueChanged'), State('grid', 'rowData'))
def rowDataUpdate(c, d):
    if d:
        return json.dumps(d)

@app.callback(Output('grid', 'rowData'), Output('addRow','n_clicks'), Output('addRow_notAsync', 'n_clicks'),
              Input('reset','n_clicks'))
def reset(n):
    if n > 0:
        return rowData, 0, 0
    return no_update, no_update, no_update

@app.callback(Output('grid', 'rowTransaction'), Input('addRow', 'n_clicks'), Input('addRow_notAsync', 'n_clicks'))
def addRows(n, n2):
    if n or n2:
        if ctx.triggered_id == 'addRow':
            return {'add': [extraData[n-1]]}
        if ctx.triggered_id == 'addRow_notAsync':
            return {'add': [extraData[n2-1]], 'async': False}


if __name__ == "__main__":
    app.run_server(debug=True, port=12345)
```

If you switch the first input from `cellValueChanged` to `rowData` it stops reflecting the changes. When using async `rowTransaction` the `rowData` gets out of sync, even with itself.

**Comment by BSd3v** [comment]
> @AnnMarieW are you saying if you make a callback with both `cellValueChanged` and `rowData` as inputs, `rowData` is not yet updated when the callback fires? Can you give an example app? Is this about async updates perhaps?
> 
> Feels like `cellValueChanged` should be enough of a trigger, but another option could be alongside `cellValueChanged` to also do `setProps({rowData: [...rowData]})` so it's a new array. That might cause an infinite loop though, would need to try it.

Setting as a new array doesnt successfully circumvent the binding. 👎

**Comment by BSd3v** [comment]
Even when using full row editing, the `cellValueChanged` gets triggered on the last one upon exit, so a trigger based upon that would work.

For this to work, the callback should have inputs from _both_ `cellValueChanged` and `rowData` to work properly. I've also fixed the async issue, there is an event `asyncTransactionsFlushed` that we can use to sync the `rowData` with the table.

@alexcjohnson

**Comment by AnnMarieW** [comment]
I actually didn't try it with both `cellValueChanged` and`rowData` - and I can confirm that it works fine that way.  I'll add that to the docs, then I think it's OK to close this issue.  Thanks!
