### ISSUE TITLE
Version/revision  sync / docs / getting started

### ISSUE THREAD

**Issue by jcuypers** [plotly/dash-ag-grid#94]
Hi, 

Might be good to have a way to automatically update the revision / versions from one location so everything stays in sync.

Getting started : 
`pip install dash-ag-grid==2.0.0a3`

Warning banner:
2.0.0a3

header upper right 2.0.0a4
![image](https://user-images.githubusercontent.com/46247/225622504-7b2662f9-08b4-4fc5-830e-8047a78dae69.png)

**Comment by BSd3v** [comment]
Good catch. Thank you for bringing to our attention. 😁
