### ISSUE TITLE
autoSizeAllColumns bug

### ISSUE THREAD

**Issue by AnnMarieW** [plotly/dash-ag-grid#99]
Error when updating  `autoSizeAllColumns` prop in  a callback:

![image](https://user-images.githubusercontent.com/72614349/226110756-6d6845af-53a2-4fde-b098-1368faade52e.png)

Here is MRE
```python

from dash import Dash, html, Input, Output
import dash_ag_grid as dag
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv")

app = Dash(__name__)

grid = dag.AgGrid(
    id="size-grid",
    rowData=df.to_dict("records"),
    columnDefs=[{"field": i, "id": i} for i in df.columns],
    defaultColDef={"resizable": True},
    columnSize="sizeToFit",
)


app.layout = html.Div([
    html.Button("Auto Size", id="auto-size"),
    grid
])


@app.callback(
    Output("size-grid", "autoSizeAllColumns"),
    Input("auto-size", "n_clicks"),
   # prevent_initial_call=True
)
def change_size(_):
    return True


if __name__ == "__main__":
    app.run_server(debug=True)


```

**Comment by BSd3v** [comment]
This isn’t a bug, the grid isn’t ready, that is why it can’t be triggered immediately. 

This needs to be delayed until the grid is ready if provided.

**Comment by AnnMarieW** [comment]
True - if you un-comment  the `prevent_initial_call=True` in the example, the error goes away.  However, it's not always possible to prevent callbacks from firing in a multi-page apps.  Can the this error be handled in the component?  https://github.com/plotly/dash-ag-grid/blob/dev/src/lib/fragments/AgGrid.react.js#L844

**Comment by BSd3v** [comment]
That’s what my previous secondary statement was about. 

This should be true for all event triggers.
